#!/usr/bin/env python3
"""svg_census.py — every SVG this app draws, and whether its ink agrees with its record (WP-14.1).

    python3 tests/svg_census.py              # the summary table
    python3 tests/svg_census.py --json       # every row, machine-readable
    python3 tests/svg_census.py --write-doc  # regenerate the tables in docs/fidelity.md

WHY A CENSUS AND NOT A TEST FILE. Lucas asked for "all areas of the app that generate SVGs ...
every surface covered", and a claim about ALL surfaces is only as good as the list it is made
over. So the list is data here -- `REGISTRY` -- and `tests/test_svg_census.py` greps the tree for
anything that emits SVG and fails on a file the registry does not name. A new surface cannot
join the app without either a row here or a stated reason it is out of scope.

EVERY CHECK HAS THREE ANSWERS: agrees, disagrees (with the figures), COULD NOT EVALUATE (with the
reason). A check that finds nothing to evaluate is a check that evaluated nothing; its
population is printed beside its verdicts so a zero reads as a zero and not as a pass.

THE KNOWN DISAGREEMENTS ARE HELD BY IDENTITY, WITH THEIR FIGURES. `tests/fixtures/
ink_known_disagreements.json` names every row that disagrees today and what it measured, and the
test holds the live set EQUAL to it: a new disagreement fails, a fixed one must be removed from
the file, and one whose figures moved must be re-pinned by a commit that says why. That is the one-way door
`build/measured_unsourced_grandfathered.json` already uses, chosen over `xfail` and over a red
build because a suite already red for one cause cannot report a second.
"""
import argparse
import json
import math
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "build"))

import ink_surfaces as SURF  # noqa: E402
import inkread as IR  # noqa: E402

DOC = os.path.join(ROOT, "docs", "fidelity.md")
KNOWN = os.path.join(HERE, "fixtures", "ink_known_disagreements.json")

# ------------------------------------------------------------------ the registry
# role: "producer" draws architectural SVG; "carrier" moves another producer's SVG to a reader
# without drawing; "helper" builds path data a producer emits; "out-of-scope" is not an
# architectural drawing and is listed so the claim "every surface" is checkable.
REGISTRY = [
    {"id": "profile-plates", "file": "build/render_profile.py", "role": "producer",
     "surface": "73 moulding-profile plates committed under assets/generated/",
     "served": "/corpus/assets/generated/*.svg, tdl_find_assets, /api/assets"},
    {"id": "orders-tool", "file": "build/orders_template.html", "role": "producer",
     "surface": "the order-drawing tool dist/orders.html (half section, mirrored elevation)",
     "served": "dist/orders.html (generated by build/render_orders.py)"},
    {"id": "proportions-plate", "file": "workbench/app/src/surfaces/Proportions.jsx", "role": "producer",
     "surface": "the workbench Proportions plate (half section of each order pack)",
     "served": "workbench surface; paths from corpus.proportions_with_members"},
    {"id": "elevation", "file": "build/render_elevation.py", "role": "producer",
     "surface": "elevation sheets, each with an eave-cornice profile inset",
     "served": "POST /api/drawings/elevation, the Drawing Set, the Round"},
    {"id": "section", "file": "build/render_section.py", "role": "producer",
     "surface": "the building section and the bearing diagram",
     "served": "POST /api/drawings/section and /bearing"},
    {"id": "roof", "file": "build/render_roof.py", "role": "producer",
     "surface": "the roof plan", "served": "POST /api/drawings/roof"},
    {"id": "plan", "file": "build/render_plan.py", "role": "producer",
     "surface": "the plan sheet (presentation and working registers)",
     "served": "POST /api/drawings/plan, tdl_place_plan, the Drawing Set"},
    {"id": "bench-sheet", "file": "workbench/app/src/sheet/Sheet.jsx", "role": "producer",
     "surface": "the Plan Workbench's live sheet, drawn in JavaScript",
     "served": "workbench surface"},
    {"id": "transcription", "file": "workbench/app/src/surfaces/Transcription.jsx", "role": "producer",
     "surface": "the Transcription draft canvas (a person's own tracing)",
     "served": "workbench surface"},
    {"id": "profiles-geometry", "file": "build/profiles.py", "role": "helper",
     "surface": "the moulding constructions and their SVG path serialiser",
     "served": "used by the profile plates, the orders tool, the Proportions plate, the elevation inset"},
    {"id": "drawing-set", "file": "workbench/app/src/surfaces/DrawingSet.jsx", "role": "carrier",
     "surface": "injects the server's plan/elevation/section/roof SVG; offers it for download",
     "served": "workbench surface"},
    {"id": "export-details", "file": "workbench/app/src/surfaces/ExportDetails.jsx", "role": "carrier",
     "surface": "downloads the server's presentation-register SVG", "served": "workbench surface"},
    {"id": "round-plates", "file": "workbench/app/src/round/RoundPlate.jsx", "role": "carrier",
     "surface": "lays the Python plates over the 3D model by their data-frame",
     "served": "workbench surface"},
    {"id": "taxonomy-timeline", "file": "build/template.html", "role": "out-of-scope",
     "reason": "the taxonomy page's timeline and ruler: a chart of dates, not a drawing of a building"},
    {"id": "phylogeny", "file": "workbench/app/src/surfaces/Phylogeny.jsx", "role": "out-of-scope",
     "reason": "the lineage graph: a diagram of influence between styles"},
    {"id": "atlas", "file": "workbench/app/src/surfaces/phylo/MapView.jsx", "role": "out-of-scope",
     "reason": "the atlas: coastlines and a graticule, not architecture"},
    {"id": "tokens", "file": "workbench/app/src/theme/tokens.css", "role": "out-of-scope",
     "reason": "a stylesheet that names <svg> in a comment; it draws nothing"},
]

# WHAT COUNTS AS EMITTING SVG. The first version matched `<svg` alone and was blind to a React
# component that returns a `<path>` or a `<line>` inside its parent's `<svg>` -- it never writes
# the root element, and it is exactly where a second spelling of a mark would grow. So a primitive
# counts too, but only followed by an ATTRIBUTE: `<path>[]` in a docstring and `(?P<path>` in a
# route regex are prose and code, not ink. A carrier that injects a server's SVG is found by
# `dangerouslySetInnerHTML`, because it writes no primitive of its own.
_EMIT = re.compile(r"<(svg|path|polyline|polygon|circle|ellipse|line|rect)\s+[a-zA-Z]|"
                   r"createElementNS|image/svg\+xml|dangerouslySetInnerHTML")
_SKIP = re.compile(r"^(tests/|docs/|dist/|assets/|workbench/app/e2e/|workbench/server/tests/|"
                   r"workbench/app/dist/)|node_modules|\.(md|json|svg|txt|b64)$|\.test\.m?js$")


def emitters(root=ROOT):
    """Every tracked or new file (never a walk: WP-13.2's rule) that mentions an SVG emitter."""
    files = subprocess.run(["git", "ls-files", "-co", "--exclude-standard"], cwd=root,
                           capture_output=True, text=True, check=True).stdout.split()
    out = []
    for f in sorted(files):
        if _SKIP.search(f):
            continue
        try:
            with open(os.path.join(root, f), encoding="utf-8", errors="ignore") as fh:
                if _EMIT.search(fh.read()):
                    out.append(f)
        except (IsADirectoryError, FileNotFoundError):
            continue
    return out


def unregistered(root=ROOT):
    named = {r["file"] for r in REGISTRY}
    return [f for f in emitters(root) if f not in named]


# ------------------------------------------------------------------ the checks
CHECKS = {}


def check(cid, surface, statement, population):
    def wrap(fn):
        CHECKS[cid] = {"id": cid, "surface": surface, "statement": statement,
                       "population": population, "fn": fn}
        return fn
    return wrap


def row(cid, subject, verdict, detail=""):
    assert verdict in ("agrees", "disagrees", "cne"), verdict
    return {"check": cid, "subject": subject, "verdict": verdict, "detail": detail}


_PLATES = None


def _profile_assets():
    """The committed plates, read back from the files a reader is served."""
    global _PLATES
    if _PLATES is None:
        doc = json.load(open(os.path.join(ROOT, "assets", "manifest.json")))
        _PLATES = []
        for a in doc["assets"]:
            g = a.get("generated_from")
            if not g:
                continue
            path = os.path.join(ROOT, a["file"]["path"])
            svg = open(path).read()
            _PLATES.append((a, g, SURF.ProfilePlate(svg),
                            SURF.profile_record(g["pack"], (g.get("parameters") or {}).get("assembly"),
                                                g.get("module_in") or 6.0)))
    return _PLATES


def _unreadable(pl):
    """Why this plate's geometry cannot be read back, or None. A plate that states no frame, or
    whose silhouette is not one filled path, is COULD NOT EVALUATE with that reason -- never a
    crash, which would stop every later check, and never a pass."""
    if pl.plate is None:
        return "the plate states no data-frame, so its pixels cannot be read as inches"
    if pl.outline is None:
        return "%d filled paths where one silhouette was expected" % pl.n_outlines
    return None


def _fig(pattern, text):
    m = re.search(pattern, text)
    return float(m.group(1)) if m else None


@check("P1", "profile-plates", "the column diameter a plate prints is the diameter it is drawn at",
       "every committed profile plate")
def p1():
    out = []
    for a, g, pl, rec in _profile_assets():
        got = _fig(r"at a ([\d.]+)″ column", pl.flat_text)
        want = rec["lower_diameter_in"]
        if got is None:
            out.append(row("P1", a["id"], "cne", "no column diameter printed"))
        elif abs(got - want) > 0.5:
            out.append(row("P1", a["id"], "disagrees", "prints %g in, drawn at %g in" % (got, want)))
        else:
            out.append(row("P1", a["id"], "agrees"))
    return out


@check("P2", "profile-plates", "the relief a plate prints is the relief its ink draws",
       "every committed profile plate")
def p2():
    out = []
    for a, g, pl, rec in _profile_assets():
        got = _fig(r"([\d.]+)″ of relief", pl.flat_text)
        # A plate whose ink draws no relief SAYS so in words rather than printing a figure
        # (WP-14.2), and "no relief" is a claim of zero that the ink can contradict -- read it as
        # one, never as a plate that printed nothing.
        if got is None and re.search(r"\bno relief\b", pl.flat_text):
            got = 0.0
        why = _unreadable(pl) or (None if got is not None else "no relief printed")
        if why:
            out.append(row("P2", a["id"], "cne", why))
            continue
        drawn = max(u for u, v in pl.points()) - pl.naked()
        if abs(got - drawn) > 0.011:
            out.append(row("P2", a["id"], "disagrees", "prints %.2f in, draws %.2f in" % (got, drawn)))
        else:
            out.append(row("P2", a["id"], "agrees"))
    return out


@check("P3", "profile-plates", "no ink falls inside the assembly's own naked (a moulding bitten "
       "into the member it stands on)", "every committed profile plate")
def p3():
    out = []
    for a, g, pl, rec in _profile_assets():
        if _unreadable(pl):
            out.append(row("P3", a["id"], "cne", _unreadable(pl)))
            continue
        worst = pl.naked() - min(u for u, v in pl.points())
        if worst > 0.01:
            out.append(row("P3", a["id"], "disagrees", "ink %.2f in inside the naked" % worst))
        else:
            out.append(row("P3", a["id"], "agrees"))
    return out


@check("P4", "profile-plates", "every mark of ink is inside the plate's viewBox",
       "every committed profile plate")
def p4():
    out = []
    for a, g, pl, rec in _profile_assets():
        x0, y0, w, h = pl.ink.viewbox()
        bad = 0
        for it in pl.ink.items:
            if it.tag == "text" or not it.cmds:
                continue
            for x, y in it.points(n=24):
                if x < x0 - 0.5 or y < y0 - 0.5 or x > x0 + w + 0.5 or y > y0 + h + 0.5:
                    bad += 1
        out.append(row("P4", a["id"], "disagrees" if bad else "agrees",
                       ("%d sampled point(s) outside the viewBox" % bad) if bad else ""))
    return out


@check("P5", "profile-plates", "every member boundary the record states is a drawn vertex, and "
       "the drawn height is the stated height", "every committed profile plate")
def p5():
    out = []
    for a, g, pl, rec in _profile_assets():
        if _unreadable(pl):
            out.append(row("P5", a["id"], "cne", _unreadable(pl)))
            continue
        vs = sorted({round(p[1][1], 4) for p in pl.segments_in_model()} |
                    {round(p[2][1], 4) for p in pl.segments_in_model()})
        missing = []
        for m in rec["members"]:
            if rec["side_by_side"]:
                continue
            for b in (m["y_bottom_in"], m["y_top_in"]):
                if not any(abs(b - v) <= 0.01 for v in vs):
                    missing.append("%s@%.3f" % (m["id"], b))
        pts = pl.points()
        span = max(v for u, v in pts) - min(v for u, v in pts)
        want = max(m["y_top_in"] for m in rec["members"]) - min(m["y_bottom_in"] for m in rec["members"])
        if missing or abs(span - want) > 0.01:
            out.append(row("P5", a["id"], "disagrees",
                           "drawn %.3f in against %.3f; boundaries not drawn: %s"
                           % (span, want, ", ".join(sorted(set(missing))[:6]) or "none")))
        else:
            out.append(row("P5", a["id"], "agrees"))
    return out


@check("P6", "profile-plates", "a member whose face is at its mid-height (a step or a half round) "
       "is drawn out to the face its record states", "members with a published projection")
def p6():
    out = []
    PROF = SURF._mod("profiles")
    for a, g, pl, rec in _profile_assets():
        if _unreadable(pl):
            out.append(row("P6", a["id"], "cne", _unreadable(pl)))
            continue
        naked = pl.naked()
        datum = pl.plate.get("datum")
        bad = []
        judged = 0
        for m in rec["members"]:
            if rec["side_by_side"] or not rec["published"].get(m["id"]):
                continue
            if (m.get("profile") or "flat") not in SURF.FACE_AT_MID:
                continue
            want = PROF.outer_face(naked, m.get("projection_in") or 0.0, datum == "axis")
            got = pl.extent_at((m["y_bottom_in"] + m["y_top_in"]) / 2.0)
            judged += 1
            if got is None or abs(got - want) > 0.02:
                bad.append("%s drawn to %s, record %.3f" % (m["id"], "nothing" if got is None else "%.3f" % got, want))
        if not judged:
            out.append(row("P6", a["id"], "cne", "no member of a kind this check reads"))
        elif bad:
            out.append(row("P6", a["id"], "disagrees", "; ".join(bad[:4])))
        else:
            out.append(row("P6", a["id"], "agrees", "%d member(s)" % judged))
    return out


@check("P7", "profile-plates", "a member the record gives no projection for is SAID to have "
       "none, not drawn as though measured flush -- and a plate where every member publishes one "
       "says that", "every committed profile plate")
def p7():
    out = []
    for a, g, pl, rec in _profile_assets():
        n = sum(1 for m in rec["members"] if not rec["published"].get(m["id"]))
        if not n:
            # THE COUNT GOES ON EVERY PLATE (decision 2, WP-14.2): silence on a complete plate
            # reads exactly like silence on a plate nobody checked.
            said = re.search(r"ALL (\d+) MEMBER\(S\) PUBLISH A PROJECTION", pl.flat_text.upper())
            if said and int(said.group(1)) == len(rec["members"]):
                out.append(row("P7", a["id"], "agrees", "all %d published, said" % len(rec["members"])))
            else:
                out.append(row("P7", a["id"], "disagrees",
                               "every member publishes a projection and the plate %s"
                               % ("says %s" % said.group(1) if said else "does not say so")))
            continue
        said = re.search(r"(\d+) MEMBER\(S\)[^.]*NO PROJECTION PUBLISHED", pl.flat_text.upper())
        if said and int(said.group(1)) == n:
            out.append(row("P7", a["id"], "agrees", "%d unpublished, said" % n))
        else:
            out.append(row("P7", a["id"], "disagrees",
                           "%d member(s) carry no projection in the record; the plate %s"
                           % (n, "says %s" % said.group(1) if said else "says nothing")))
    return out


@check("P8", "profile-plates", "a member the plate calls NOT CONSTRUCTED has no curve drawn "
       "for it", "plates holding a volute or acanthus member")
def p8():
    out = []
    for a, g, pl, rec in _profile_assets():
        unc = [m for m in rec["members"] if (m.get("profile") or "") in SURF.UNCONSTRUCTED]
        if not unc:
            continue
        if _unreadable(pl):
            out.append(row("P8", a["id"], "cne", _unreadable(pl)))
            continue
        curved = sum(len(pl.segments_within(m["y_bottom_in"], m["y_top_in"])) for m in unc)
        if curved:
            out.append(row("P8", a["id"], "disagrees",
                           "%d curve(s) inked for %d member(s) the plate says are not constructed"
                           % (curved, len(unc))))
        else:
            out.append(row("P8", a["id"], "agrees"))
    return out


@check("P9", "profile-plates", "a plate showing another authority's members says whose they are",
       "every committed profile plate")
def p9():
    out = []
    for a, g, pl, rec in _profile_assets():
        pack = g["pack"]
        owner = rec["owner"]
        says = "INHERITED" in pl.flat_text
        names = owner and owner in pl.flat_text
        if owner and owner != pack:
            ok = says and names
        else:
            ok = not says
        out.append(row("P9", a["id"], "agrees" if ok else "disagrees",
                       "" if ok else "owner %s; plate %s INHERITED" % (owner, "says" if says else "does not say")))
    return out


@check("P10", "profile-plates", "a member whose record confidence is not high is marked as such "
       "on the plate -- in its own label, and by a dashed outline over its own height",
       "plates holding a medium- or low-confidence member")
def p10():
    out = []
    for a, g, pl, rec in _profile_assets():
        # an UNSTATED confidence is not a high one; every member states one today (733 of 733)
        weak = [m for m in rec["members"]
                if (rec["raw"].get(m["id"], {}).get("confidence") or "unstated") != "high"]
        if not weak:
            continue
        # an unstated confidence is marked as one (WP-14.2), so its word counts as a mark. The
        # mark is the LABEL's ", <level> confidence" -- counting the bare phrase let the plate's
        # own footer sentence, which explains the dashes, satisfy this check by itself.
        marked = len(re.findall(r", (?:LOW|MEDIUM|UNSTATED) CONFIDENCE\b", pl.flat_text.upper()))
        # THE INK AS WELL AS THE WORDS (WP-14.2): one dashed outline per weak member with height,
        # read back through the frame and held to that member's own span up the stack.
        outlined = set()
        if pl.plate is not None:
            for it in pl.ink.select("path"):
                if "confidence" not in it.classes:
                    continue
                vs = [pl.model(p)[1] for p in it.points(n=4, lines=True)]
                for m in weak:
                    if abs(min(vs) - m["y_bottom_in"]) < 0.01 and abs(max(vs) - m["y_top_in"]) < 0.01:
                        outlined.add(m["id"])
        tall = [m for m in weak if m["y_top_in"] - m["y_bottom_in"] > 1e-6]
        unmarked = sorted(m["id"] for m in tall if m["id"] not in outlined)
        # every weak member carries its mark in its own label, so the count must match
        if marked >= len(weak) and not unmarked:
            out.append(row("P10", a["id"], "agrees", "%d marked" % len(weak)))
        else:
            out.append(row("P10", a["id"], "disagrees",
                           "%d of %d member(s) are medium or low confidence; %d marked in words; "
                           "no dashed outline over %s" % (len(weak), len(rec["members"]), marked,
                                                           unmarked[:4] or "none missing")))
    return out


@check("P11", "profile-plates", "a curved member drawn as a straight line says so",
       "plates holding a curved profile kind")
def p11():
    out = []
    for a, g, pl, rec in _profile_assets():
        # A member whose projection is unpublished is not drawn straight: it is not constructed
        # at all, and P7 holds the plate to saying so (WP-14.2).
        curved = [m for m in rec["members"] if (m.get("profile") or "") in SURF.CURVED
                  and not rec["side_by_side"] and rec["published"].get(m["id"])]
        if not curved:
            continue
        if _unreadable(pl):
            out.append(row("P11", a["id"], "cne", _unreadable(pl)))
            continue
        straight = [m["id"] for m in curved
                    if not pl.segments_within(m["y_bottom_in"], m["y_top_in"])]
        if not straight:
            out.append(row("P11", a["id"], "agrees"))
            continue
        said = re.search(r"(\d+) CURVED MEMBER\(S\) DRAWN STRAIGHT", pl.flat_text.upper())
        if said and int(said.group(1)) == len(straight):
            out.append(row("P11", a["id"], "agrees", "%d straight, said" % len(straight)))
        else:
            out.append(row("P11", a["id"], "disagrees",
                           "%s drawn straight and not said" % ", ".join(straight[:5])))
    return out


@check("P12", "profile-plates", "the committed plate is the renderer's current output",
       "every committed profile plate")
def p12():
    RP = SURF._mod("render_profile")
    out = []
    for a, g, pl, rec in _profile_assets():
        svg, _rep = RP.render(g["pack"], (g.get("parameters") or {}).get("assembly"),
                              module_in=g.get("module_in") or 6.0)
        out.append(row("P12", a["id"], "agrees" if svg + "\n" == pl.svg else "disagrees",
                       "" if svg + "\n" == pl.svg else "stale: re-run build/render_profile.py --write"))
    return out


@check("P13", "profile-plates", "a part the assembly's own members are named for, and no member "
       "records, is said on the plate -- not drawn as though the section were the whole",
       "plates whose members are named for a part no member records")
def p13():
    """Read off the RECORD's own member names, independently of `profiles.named_not_recorded`:
    four Ionic capitals record the volute's channel and fillet and no volute (WP-14.2)."""
    out = []
    parts = (("volute", "volute"), ("acanthus", "acanthus"), ("caulicol", "volute"))
    for a, g, pl, rec in _profile_assets():
        members = list(rec["raw"].values())
        profs = {(m.get("profile") or "").lower() for m in members}
        missing = [w for w, prof in parts if prof not in profs and any(
            w in ((m.get("id") or "") + " " + (m.get("name") or "")).lower() for m in members)]
        if not missing:
            continue
        unsaid = [w for w in missing if ("NOT RECORDED: THE %s" % w.upper())
                  not in pl.flat_text.upper()]
        if unsaid:
            out.append(row("P13", a["id"], "disagrees",
                           "members are named for a %s no member records, and the plate says "
                           "nothing" % ", ".join(unsaid)))
        else:
            out.append(row("P13", a["id"], "agrees", ", ".join(missing)))
    return out


# ------------------------------------------------------------------ the order stack (link 2)
# The orders tool and the Proportions plate draw a WHOLE column and entablature, stacked by the
# engine's `stack_for` and dimensioned by `dimension()` -- the orders page through a JavaScript
# port of both. These checks hold that stack to what each pack STATES, before any ink: a column
# drawn at the wrong height is wrong on every surface that draws it, and asking each surface
# separately would report one defect three times.
def _order_packs():
    PE = SURF._mod("proportion_engine")
    for pid in sorted(PE.PACKS):
        if (PE.PACKS[pid].get("kind") or "") != "order-system":
            continue
        pack = PE.resolve(pid)
        dim = PE.dimension(pack, module_in=6.0)
        heights = {a["id"]: a["y_top_in"] - a["y_bottom_in"] for a in dim["assemblies"]}
        yield pid, pack, dim, heights


@check("E1", "order-stack", "the column drawn (base + shaft + capital) is the column height the "
       "pack states", "order packs stating a column height")
def e1():
    out = []
    for pid, pack, dim, H in _order_packs():
        col = dim["totals"].get("column_height_in")
        if not col:
            continue
        if not all(a in H for a in ("base", "shaft", "capital")):
            out.append(row("E1", pid, "cne", "the stack holds %s, not a whole column"
                           % ", ".join(sorted(H)) or "nothing"))
            continue
        drawn = sum(H[a] for a in ("base", "shaft", "capital"))
        if abs(drawn - col) > 0.01:
            out.append(row("E1", pid, "disagrees", "states %.2f in, draws %.2f in (at a 6 in module)"
                           % (col, drawn)))
        else:
            out.append(row("E1", pid, "agrees"))
    return out


@check("E2", "order-stack", "the entablature drawn is the one the pack itself states",
       "order packs that state a whole entablature")
def e2():
    out = []
    PE = SURF._mod("proportion_engine")
    for pid, pack, dim, H in _order_packs():
        stated = dim["totals"].get("entablature_height_in")
        if not stated:
            continue
        drawn = sum(H.get(a, 0.0) for a in ("architrave", "frieze", "cornice", "entablature"))
        owner = PE.assembly_owner(pid, "entablature")
        if abs(drawn - stated) > 0.01:
            out.append(row("E2", pid, "disagrees",
                           "%s states %.2f in; the stack draws %.2f in from %s's %s"
                           % (owner, stated, drawn, PE.assembly_owner(pid, "cornice") or "nobody",
                              "architrave, frieze and cornice" if "cornice" in H else "entablature")))
        else:
            out.append(row("E2", pid, "agrees"))
    return out


@check("E3", "order-stack", "an assembly offered as an ALTERNATIVE to another is never stacked "
       "on it (Benjamin's subplinth stands a column instead of a pedestal)",
       "order packs stating a subplinth")
def e3():
    out = []
    for pid, pack, dim, H in _order_packs():
        if "subplinth" not in (pack.get("assemblies") or {}):
            continue
        stacked = [a["id"] for a in dim["assemblies"]]
        if "subplinth" in stacked and "pedestal" in stacked:
            out.append(row("E3", pid, "disagrees", "pedestal and subplinth both stacked (%.2f + %.2f in)"
                           % (H["pedestal"], H["subplinth"])))
        else:
            out.append(row("E3", pid, "agrees"))
    return out


@check("E4", "order-stack", "the pedestal die is drawn at a naked the record gives, never the "
       "1.2 x R stand-in profiles.pack_geometry takes when the base publishes no plinth",
       "order packs drawing a pedestal")
def e4():
    out = []
    for pid, pack, dim, H in _order_packs():
        asms = {a["id"]: a for a in dim["assemblies"]}
        if "pedestal" not in asms and "subplinth" not in asms:
            continue
        base = asms.get("base")
        plinth = max([m.get("projection_in") or 0.0 for m in base["members"]], default=0.0) if base else 0.0
        if plinth:
            out.append(row("E4", pid, "agrees"))
        else:
            out.append(row("E4", pid, "disagrees",
                           "the base publishes no projection, so the die is drawn at 1.2 x R, a "
                           "figure no record states"))
    return out


# ------------------------------------------------------------------ the orders page (JavaScript)
# dist/orders.html draws with code that exists nowhere else, so its ink is read by running the
# COMMITTED page's own scripts in node:vm (tests/js/orders_ink.mjs) and handing what they draw to
# inkread. Where there is no `node` every row is COULD NOT EVALUATE, never a pass.
ORDERS_PAGE = os.path.join(ROOT, "dist", "orders.html")
ORDER_DIAMETERS = (12, 24, 36)
_ORDERS = None


def _auth_order(pid):
    a, o = pid.rsplit("-", 1)
    return a, o


def _orders_run():
    """{key: {svg, info, meta}} for every order pack at every diameter, pedestal on and off, plus
    the driven cases; or a string saying why it could not run."""
    global _ORDERS
    if _ORDERS is not None:
        return _ORDERS
    if not shutil.which("node"):
        _ORDERS = "node is not installed, so the page's own scripts cannot be run"
        return _ORDERS
    RO = SURF._mod("render_orders")
    cases = []
    for pid in RO.order_pack_ids():
        a, o = _auth_order(pid)
        for d in ORDER_DIAMETERS:
            for ped in (True, False):
                cases.append({"key": "%s@%d%s" % (pid, d, "" if ped else "-noped"), "pid": pid,
                              "auth": a, "order": o, "diameter": d, "ped": ped})
    # the branch no pack reaches today: an invariant the engine could not judge
    cases.append({"key": "vignola-ionic@12-unjudged-invariant", "pid": "vignola-ionic",
                  "auth": "vignola", "order": "ionic", "diameter": 12, "ped": True,
                  "patch": "P['vignola-ionic'].invariants[0].holds = null;"})
    r = subprocess.run(["node", os.path.join(HERE, "js", "orders_ink.mjs"), ORDERS_PAGE],
                       input=json.dumps(cases), capture_output=True, text=True, timeout=600)
    if r.returncode:
        _ORDERS = "the page's scripts failed under node: " + (r.stderr.strip().splitlines() or ["?"])[-1]
        return _ORDERS
    out = json.loads(r.stdout)
    _ORDERS = {"cases": cases, "out": out}
    return _ORDERS


def _silh_model(svg):
    """The section silhouette of an orders-page drawing in its own frame's inches."""
    ink = IR.Ink(svg)
    plate = ink.frame(proj="order")
    sil = [it for it in ink.items if "silh" in it.classes and "ghost" not in it.classes]
    if plate is None or len(sil) != 1:
        return None, None
    return [IR.to_model(plate, x, y) for x, y in sil[0].points(n=24, lines=True)], ink


def _python_stack(pid, diameter, ped):
    PE = SURF._mod("proportion_engine")
    PROF = SURF._mod("profiles")
    pack = PE.resolve(pid)
    inc = [a for a in PE.stack_for(pack) if ped or a not in ("pedestal", "subplinth")]
    dim = PE.dimension(pack, module_in=diameter * PE.diameters_per_module(pack), include=inc)
    geo = PROF.pack_geometry(dim, pack.get("column"), pack.get("projection_datum"))
    pts = [p for sub in IR.sample_commands(IR.parse_path(geo["path"]), n=24, lines=True) for p in sub] \
        if geo.get("path") else []
    return dim, geo, pts


@check("O1", "orders-tool", "the committed page is what build/render_orders.py builds now",
       "the one page")
def o1():
    RO = SURF._mod("render_orders")
    have = open(ORDERS_PAGE, encoding="utf-8").read()
    ok = have == RO.build_page()
    return [row("O1", "dist/orders.html", "agrees" if ok else "disagrees",
                "" if ok else "stale: run python3 build/render_orders.py (build.py does)")]


@check("O2", "orders-tool", "the section the page draws is the height the engine dimensions, "
       "at every diameter it offers, pedestal on and off",
       "every order pack with a stack x 12/24/36 in x pedestal")
def o2():
    run = _orders_run()
    if isinstance(run, str):
        return [row("O2", "dist/orders.html", "cne", run)]
    out = []
    for c in run["cases"]:
        if c.get("patch"):
            continue
        dim, geo, _p = _python_stack(c["pid"], c["diameter"], c["ped"])
        if not dim["assemblies"]:
            continue            # `moorish-arch` states no stack: there is no section to draw
        pts, _ink = _silh_model(run["out"][c["key"]]["svg"])
        if not pts:
            out.append(row("O2", c["key"], "cne", "no single framed section silhouette"))
            continue
        drawn = max(v for u, v in pts) - min(v for u, v in pts)
        want = dim["totals"]["stack_height_in"]
        if abs(drawn - want) > 0.02:
            out.append(row("O2", c["key"], "disagrees", "draws %.2f in, the engine %.2f in" % (drawn, want)))
        else:
            out.append(row("O2", c["key"], "agrees"))
    return out


@check("O3", "orders-tool", "the section reaches as far out as the geometry Python constructed "
       "for it, scaled to the diameter drawn", "every order pack with a stack x 12/24/36 in x pedestal")
def o3():
    run = _orders_run()
    if isinstance(run, str):
        return [row("O3", "dist/orders.html", "cne", run)]
    out = []
    for c in run["cases"]:
        if c.get("patch"):
            continue
        dim, geo, ppts = _python_stack(c["pid"], c["diameter"], c["ped"])
        if not dim["assemblies"]:
            continue
        pts, _ink = _silh_model(run["out"][c["key"]]["svg"])
        if not pts or not ppts:
            out.append(row("O3", c["key"], "cne", "no section drawn or no geometry constructed"))
            continue
        drawn, want = max(u for u, v in pts), max(u for u, v in ppts)
        if abs(drawn - want) > 0.02:
            out.append(row("O3", c["key"], "disagrees", "reaches %.2f in, the geometry %.2f in" % (drawn, want)))
        else:
            out.append(row("O3", c["key"], "agrees"))
    return out


@check("O4", "orders-tool", "an invariant the engine could not judge is not printed FAIL",
       "driven: one invariant set unjudged (every one of 169 holds today)")
def o4():
    run = _orders_run()
    if isinstance(run, str):
        return [row("O4", "dist/orders.html", "cne", run)]
    info = run["out"]["vignola-ionic@12-unjudged-invariant"]["info"]
    first = re.search(r'<div class="inv"><span class="m ([a-z]+)">([^<]*)</span>', info)
    if not first:
        return [row("O4", "unjudged-invariant", "cne", "the page printed no invariant")]
    shown = first.group(2)
    if shown.upper() == "FAIL":
        return [row("O4", "unjudged-invariant", "disagrees",
                    "an invariant whose verdict is null is printed FAIL, a failure nobody measured")]
    return [row("O4", "unjudged-invariant", "agrees", "printed %r" % shown)]


@check("O5", "orders-tool", "every order pack the page carries can be reached from its controls",
       "every order pack in the page")
def o5():
    run = _orders_run()
    if isinstance(run, str):
        return [row("O5", "dist/orders.html", "cne", run)]
    reach = set(run["out"]["__reachable"])
    RO = SURF._mod("render_orders")
    return [row("O5", pid, "agrees" if pid in reach else "disagrees",
                "" if pid in reach else "carried in the page's data and selectable by no button")
            for pid in RO.order_pack_ids()]


def _flute_fracs(n):
    """Where the arrises of n evenly spaced flutes fall across a half elevation, as a fraction of
    the radius, for both ways of setting them out: a flute on the axis, or an arris on it."""
    step = 2 * math.pi / n
    a = sorted(round(math.sin((k + 0.5) * step), 4) for k in range(n) if (k + 0.5) * step < math.pi / 2)
    b = sorted(round(math.sin(k * step), 4) for k in range(1, n) if k * step < math.pi / 2)
    return a, b


@check("O6", "orders-tool", "the flute lines on the elevation fall where the stated number of "
       "flutes projects", "fluted order packs, at 12 in, pedestal on")
def o6():
    run = _orders_run()
    if isinstance(run, str):
        return [row("O6", "dist/orders.html", "cne", run)]
    PE = SURF._mod("proportion_engine")
    out = []
    for c in run["cases"]:
        if c.get("patch") or c["diameter"] != 12 or not c["ped"]:
            continue
        pack = PE.resolve(c["pid"])
        n = ((pack.get("column") or {}).get("fluting") or {}).get("count")
        if not n:
            continue
        ink = IR.Ink(run["out"][c["key"]]["svg"])
        plate = ink.frame(proj="order")
        lines = [it for it in ink.select("path") if (it.style.get("stroke") or "").startswith("rgba(216,178,106,.16")]
        R = c["diameter"] / 2.0
        feet = sorted(round(abs(IR.to_model(plate, *it.points(n=1, lines=False)[0])[0]) / R, 4) for it in lines)
        a, b = _flute_fracs(n)
        ok = any(len(feet) == len(want) and all(abs(x - y) < 0.02 for x, y in zip(feet, want)) for want in (a, b))
        if ok:
            out.append(row("O6", c["pid"], "agrees", "%d flutes" % n))
        else:
            out.append(row("O6", c["pid"], "disagrees",
                           "%d flutes stated; %d lines drawn at %s of the radius, where they project "
                           "to %s" % (n, len(feet), feet[:4] + (["..."] if len(feet) > 4 else []), a)))
    return out


def _orders_said(info):
    """The orders page's own disclosures (WP-14.2), as one line of text."""
    return " ".join(re.sub(r"<[^>]+>", "", t)
                    for t in re.findall(r'<p class="note disclose">(.*?)</p>', info, flags=re.S))


def _orders_marks(svg, cls):
    """How many separate marks of one class the drawing inks: one subpath each."""
    return sum(1 for it in IR.Ink(svg).items if cls in it.classes
               for c in (it.cmds or []) if c[0] == "M")


def _orders_disclosures(cid, want_of, cls, said_re):
    """One row per order pack with a stack, at 12 in with the pedestal: the marks the page inks for
    what Python lists, and the count its panel says, against Python's own list."""
    run = _orders_run()
    if isinstance(run, str):
        return [row(cid, "dist/orders.html", "cne", run)]
    out = []
    for c in run["cases"]:
        if c.get("patch") or c["diameter"] != 12 or not c["ped"]:
            continue
        dim, geo, _p = _python_stack(c["pid"], c["diameter"], c["ped"])
        if not dim["assemblies"]:
            continue
        got = run["out"][c["key"]]
        want = want_of(dim, geo)
        said_text = _orders_said(got["info"])
        m = re.search(said_re, said_text)
        # silence is a count of 0 only where there is nothing to count; O7 holds the page to
        # saying so where that nothing is every member publishing a projection
        said = int(m.group(1)) if m else (0 if not want else None)
        inked = _orders_marks(got["svg"], cls) if cls else want
        if said == want and inked == want:
            out.append(row(cid, c["pid"], "agrees", "%d" % want))
        else:
            out.append(row(cid, c["pid"], "disagrees",
                           "Python lists %d; the page inks %d and says %s" % (want, inked, said)))
    return out


@check("O7", "orders-tool", "a member the record publishes no projection for is bracketed at its "
       "naked on the orders page and counted in its panel -- and a stack where every member "
       "publishes one says that", "every order pack with a stack, at 12 in with the pedestal")
def o7():
    def want(dim, geo):
        return len(geo.get("unpublished") or [])

    rows = _orders_disclosures("O7", want, "unpub",
                               r"(\d+) member\(s\) drawn as a dashed bracket at the naked")
    # The all-published half: the page must SAY it, not merely be silent (decision 2).
    run = _orders_run()
    if isinstance(run, str):
        return rows
    for r_ in rows:
        if r_["verdict"] != "agrees" or r_["detail"] != "0":
            continue
        key = "%s@12" % r_["subject"]
        dim, _g, _p = _python_stack(r_["subject"], 12, True)
        n = sum(len(a["members"]) for a in dim["assemblies"])
        m = re.search(r"All (\d+) member\(s\) publish a projection", _orders_said(run["out"][key]["info"]))
        if not m or int(m.group(1)) != n:
            r_["verdict"] = "disagrees"
            r_["detail"] = "every member publishes a projection and the page %s" % (
                "says %s" % m.group(1) if m else "does not say so")
    return rows


@check("O8", "orders-tool", "a member the orders page calls NOT CONSTRUCTED is drawn as its dashed "
       "envelope and counted", "every order pack with a stack, at 12 in with the pedestal")
def o8():
    return _orders_disclosures("O8", lambda dim, geo: len(geo.get("unconstructed") or []),
                               "envelope", r"(\d+) member\(s\) NOT CONSTRUCTED")


@check("O9", "orders-tool", "a curved member the orders page draws as a straight line is counted "
       "as one", "every order pack with a stack, at 12 in with the pedestal")
def o9():
    return _orders_disclosures("O9", lambda dim, geo: len(geo.get("drawn_straight") or []),
                               None, r"(\d+) CURVED MEMBER\(S\) DRAWN STRAIGHT")


@check("O10", "orders-tool", "the datum the orders page states for each assembly is the datum "
       "that assembly was drawn on", "every order pack with a stack, at 12 in with the pedestal")
def o10():
    run = _orders_run()
    if isinstance(run, str):
        return [row("O10", "dist/orders.html", "cne", run)]
    out = []
    for c in run["cases"]:
        if c.get("patch") or c["diameter"] != 12 or not c["ped"]:
            continue
        dim, geo, _p = _python_stack(c["pid"], c["diameter"], c["ped"])
        if not dim["assemblies"]:
            continue
        drawn = {a["id"]: (geo.get("assembly_datum") or {}).get(a["id"]) for a in dim["assemblies"]}
        out.append(_datum_rows("O10", c["pid"], drawn, _orders_said(run["out"][c["key"]]["info"])))
    return out


# ------------------------------------------------------------------ the Proportions plate (JavaScript)
# The workbench plate draws Python's face paths inside a frame and beside words that
# workbench/app/src/proportions/plate.js computes. That module is run by tests/js/
# proportions_plate.mjs on exactly the data corpus.proportions_with_members serves.
_PLATEJS = None


def _plate_run():
    global _PLATEJS
    if _PLATEJS is not None:
        return _PLATEJS
    if not shutil.which("node"):
        _PLATEJS = "node is not installed, so plate.js cannot be run"
        return _PLATEJS
    sys.path.insert(0, os.path.join(ROOT, "workbench", "server"))
    import corpus  # noqa: E402  (workbench/server/corpus.py; needs no web framework)
    PE = SURF._mod("proportion_engine")
    served = {}
    for pid in sorted(PE.PACKS):
        if (PE.PACKS[pid].get("kind") or "") == "order-system":
            served[pid] = corpus.proportions_with_members(pid, column_diameter=12)
    r = subprocess.run(["node", os.path.join(HERE, "js", "proportions_plate.mjs")],
                       input=json.dumps(served), capture_output=True, text=True, timeout=300)
    if r.returncode:
        _PLATEJS = "plate.js failed under node: " + (r.stderr.strip().splitlines() or ["?"])[-1]
        return _PLATEJS
    _PLATEJS = {"served": served, "plate": json.loads(r.stdout)}
    return _PLATEJS


def _plate_rows(cid):
    run = _plate_run()
    if isinstance(run, str):
        return None, [row(cid, "proportions-plate", "cne", run)]
    return run, None


@check("R1", "proportions-plate", "the plate's frame holds its own ink (the dimension gutter "
       "begins where the widest moulding ends)", "order packs the plate draws, at 12 in")
def r1():
    run, bad = _plate_rows("R1")
    if bad:
        return bad
    out = []
    for pid, P in sorted(run["plate"].items()):
        if P is None:
            continue
        g = run["served"][pid].get("geometry") or {}
        if not g.get("path"):
            out.append(row("R1", pid, "cne", "no geometry served"))
            continue
        f = P["f"]
        ink = max(x for sub in IR.sample_commands(IR.parse_path(g["path"]), n=24, lines=True)
                  for x, y in sub) * f
        if ink > P["maxX"] + 0.01:
            out.append(row("R1", pid, "disagrees", "frame %.2f in, the ink reaches %.2f in" % (P["maxX"], ink)))
        else:
            out.append(row("R1", pid, "agrees"))
    return out


@check("R2", "proportions-plate", "the members the plate says publish no projection are exactly "
       "the members whose record states none (the shaft's own body, which is the column, excepted)",
       "order packs the plate draws, at 12 in")
def r2():
    run, bad = _plate_rows("R2")
    if bad:
        return bad
    PE = SURF._mod("proportion_engine")
    out = []
    for pid, P in sorted(run["plate"].items()):
        if P is None:
            continue
        pack = PE.resolve(pid)
        record = set()
        for aid, a in (pack.get("assemblies") or {}).items():
            ms = a.get("members", [])
            # The shaft's tallest member IS the column: its face is the radius the pack publishes
            # as its diameter, so whether it carries a projection figure of its own does not arise
            # (palladio-doric and -tuscan leave it null). Read off the record's own heights here,
            # not off whichever rule the geometry uses to find it.
            body = max(ms, key=lambda m: m.get("height_parts") or 0)["id"] if aid == "shaft" and ms else None
            for m in ms:
                if m.get("projection_parts") is None and m["id"] != body:   # absent, or null
                    record.add("%s.%s" % (aid, m["id"]))
        drawn = {b["key"] for b in P["bands"]}
        record &= drawn                     # only what this plate draws can be counted on it
        said = set(P["unrecorded"])
        if said == record:
            out.append(row("R2", pid, "agrees", "%d" % len(said)))
        else:
            out.append(row("R2", pid, "disagrees",
                           "says %d; the record gives no figure for %d; said and published: %s; "
                           "unpublished and unsaid: %s" % (len(said), len(record),
                                                           sorted(said - record)[:3], sorted(record - said)[:3])))
    return out


_DATUM_PHRASES = (("axis", "from the axis for the "),
                  ("naked", "from each member\u2019s own naked for the "),
                  ("unjudged", "No datum can be read for the "))


def _datum_named(text):
    """{assembly: {datum, ...}} as a sentence NAMES them -- read off the words a reader reads,
    with each datum's own phrase, and a list running to the clause's end. A plate that names one
    assembly under two datums, or none, is caught by the caller."""
    named = {}
    for datum, phrase in _DATUM_PHRASES:
        for m in re.finditer(re.escape(phrase) + r"([a-z, ]+?)(?:[;:.\u2014]| \u2014)", text or ""):
            for a in re.split(r", | and ", m.group(1).strip()):
                if a.strip():
                    named.setdefault(a.strip(), set()).add(datum)
    return named


def _datum_rows(cid, subject, drawn, sentence):
    """One row: every assembly drawn is named under exactly the datum it was drawn on."""
    named = _datum_named(sentence)
    off = sorted("%s (drawn %s, said %s)" % (a, d, "/".join(sorted(named.get(a) or ())) or "nothing")
                 for a, d in drawn.items() if named.get(a) != {d})
    if off:
        return row(cid, subject, "disagrees", "; ".join(off[:4]))
    return row(cid, subject, "agrees", "%d assemblies" % len(drawn))


@check("R3", "proportions-plate", "the datum the plate's caption states for each assembly is the "
       "datum that assembly was drawn on", "order packs the plate draws, at 12 in")
def r3():
    run, bad = _plate_rows("R3")
    if bad:
        return bad
    out = []
    for pid, P in sorted(run["plate"].items()):
        if P is None:
            continue
        served = run["served"][pid]
        datum = (served.get("geometry") or {}).get("assembly_datum") or {}
        drawn = {a["id"]: datum.get(a["id"]) for a in served.get("assemblies", [])
                 if a.get("members")}
        out.append(_datum_rows("R3", pid, drawn, P.get("datumWords")))
    return out


# ------------------------------------------------------------------ the building sheets
# Every shipped plan is placed on the DETERMINISTIC engine (`engine="heuristic"`). What these rows
# measure is how each renderer draws the record it is handed, not which house the placer found, and
# a census built on a wall-clock solver would move between runs on the same tree (CLAUDE.md:
# ratchet the deterministic figures only). The sheets are rendered into a temporary directory
# outside the repository and read back from the files, as a reader is served them.
import copy as _copy          # noqa: E402
import glob as _glob          # noqa: E402
import tempfile as _tempfile  # noqa: E402

_SHEETS = None


def _plan_files():
    return sorted(_glob.glob(os.path.join(ROOT, "plans", "*.json"))) + \
        sorted(_glob.glob(os.path.join(ROOT, "plans", "reference", "*.json")))


def _render(fn, *args, **kw):
    """Call a renderer whose signature is fn(record, path, ...) and read back what it wrote."""
    d = _tempfile.mkdtemp(prefix="svg_census_")
    out = os.path.join(d, "sheet.svg")
    try:
        fn(*args, out, **kw)
        return open(out, encoding="utf-8").read()
    finally:
        shutil.rmtree(d, ignore_errors=True)


def _sheets():
    """{plan_id: {plan, placed, section, roof, elev, faces: {face: svg}, sec_svg, roof_svg, plan_svg}}"""
    global _SHEETS
    if _SHEETS is not None:
        return _SHEETS
    G, ST, RF, EL = (SURF._mod(n) for n in ("geometry", "structure", "roof", "elevation"))
    RE, RS, RR, RP = (SURF._mod(n) for n in ("render_elevation", "render_section", "render_roof", "render_plan"))
    out = {}
    for f in _plan_files():
        plan = json.load(open(f))
        pid = os.path.basename(f)[:-5]
        placed = G.solve(_copy.deepcopy(plan), engine="heuristic")
        rec = {"plan": plan, "placed": placed, "faces": {}}
        rec["plan_svg"] = _render(RP.render, placed, register="presentation")
        rec["plan_svg_working"] = _render(RP.render, placed, register="working")
        sec = ST.build_section(placed, None, geometry_result=placed)
        if "error" not in sec:
            rec["section"] = sec
            rec["sec_svg"] = _render(RS.render_section, sec)
            rf = RF.build_roof(placed, None, section=sec)
            if "error" not in rf:
                rec["roof"] = rf
                rec["roof_svg"] = _render(RR.render_roof, rf)
                el = EL.build_elevation(placed, None, section=sec, roof=rf)
                if "error" not in el and el.get("applicable", True):
                    rec["elev"] = el
                    for face in ("S", "N", "E", "W"):
                        rec["faces"][face] = _render(RE.render_elevation, el, face=face)
        out[pid] = rec
    _SHEETS = out
    return out


def _elev_sheets():
    for pid, rec in sorted(_sheets().items()):
        for face, svg in sorted(rec["faces"].items()):
            yield pid, face, rec, svg


def _face_plate(ink):
    return next((p for p in ink.frames() if p.get("proj") == "elevation"), None)


RUNGS = {"w-hair": 0.4, "w-fine": 0.8, "w-med": 1.2, "w-prof": 1.6, "w-cut": 2.0, "w-ground": 2.4}


@check("V1", "elevation", "every mark carrying a line-weight rung is drawn at that rung's width",
       "every elevation sheet (plans x faces)")
def v1():
    out = []
    for pid, face, rec, svg in _elev_sheets():
        ink = IR.Ink(svg)
        bad, n = {}, 0
        for it in ink.items:
            rung = [c for c in it.classes if c in RUNGS]
            if not rung:
                continue
            n += 1
            got = float(it.style.get("stroke-width") or "nan")
            if abs(got - RUNGS[rung[0]]) > 1e-6:
                k = "%s at %g (rung %g)" % (" ".join(sorted(it.classes)), got, RUNGS[rung[0]])
                bad[k] = bad.get(k, 0) + 1
        subject = "%s/%s" % (pid, face)
        if not n:
            out.append(row("V1", subject, "cne", "no rung-classed mark on the sheet"))
        elif bad:
            out.append(row("V1", subject, "disagrees", "%d of %d: %s" % (
                sum(bad.values()), n, "; ".join("%s x%d" % kv for kv in sorted(bad.items())))))
        else:
            out.append(row("V1", subject, "agrees", "%d marks" % n))
    return out


def _rects(ink, *classes):
    return [it for it in ink.select("rect") if all(c in it.classes for c in classes)]


def _box(it):
    return it.bbox()


def _sidelights(ink):
    """Glass rectangles standing hard against either side of the entrance casing."""
    cs = _rects(ink, "cs")
    if not cs:
        return []
    cx0, cy0, cx1, cy1 = _box(cs[0])
    out = []
    for r in _rects(ink, "op"):
        x0, y0, x1, y1 = _box(r)
        if abs(x1 - cx0) < 0.3 or abs(x0 - cx1) < 0.3:
            out.append(r)
    return out


def _kit(style):
    RK = SURF._mod("resolve_kit")
    g = _graph()
    slots, _ = RK.resolve_slots(g, RK.chain_for(g, style), RK.scope_for(g, style))
    return slots


_G = None


def _graph():
    global _G
    if _G is None:
        _G = SURF._mod("resolve_kit").load_graph()
    return _G


# What each thing the elevation can draw IS, in the kit's vocabulary. A CLOSED table, on
# construction_vocabulary.py's precedent: a variant id is matched by the words below and nothing
# else, and a feature is forbidden only where the slot is bound forbidden or EVERY variant the
# words match is forbidden -- a kit that forbids one keyed arch and makes another canonical has
# not forbidden the keystone.
FEATURES = (
    ("water table", "water_table", None),
    ("belt course", "belt_course", None),
    ("frieze", "frieze", None),
    ("cornice", "cornice", None),
    ("modillions", "cornice", ("modillion",)),
    ("doorcase", "door_surround", ("pilasters-and-entablature",)),
    ("sidelights", "transom_sidelight", ("sidelight",)),
    ("shutters", "shutter", None),
    ("keystone", "window_head_masonry", ("keyed", "keystone")),
)


def _drawn_features(svg):
    ink = IR.Ink(svg)
    pl = _face_plate(ink)
    got = set()
    if _rects(ink, "wt", "w-prof"):
        got.add("water table")
    if _rects(ink, "wt", "w-med"):
        got.add("belt course")
    if _rects(ink, "bd", "w-prof"):
        got.add("cornice")
    if _rects(ink, "bd", "w-fine") or re.search(r"MODILLION BAND DRAWN SOLID", svg):
        got.add("modillions")
    if pl:
        for it in ink.select("line", cls="wtm"):
            (x0, y0), (x1, y1) = it.points(n=1)[0], it.points(n=1)[-1]
            if IR.to_model(pl, x0, y0)[1] > 6.0:          # above the plinth: the frieze's bed
                got.add("frieze")
    if _rects(ink, "cs"):
        got.add("doorcase")
    if _sidelights(ink):
        got.add("sidelights")
    if _rects(ink, "sh"):
        got.add("shutters")
    for r in _rects(ink, "arch"):
        got.add("keystone")
    return got


def _forbidden(slots, slot, words):
    """None if the kit does not forbid it; else the node the prohibition comes from."""
    r = slots.get(slot)
    if not r:
        return None
    src = r.get("_source") or "?"
    if r.get("binding") == "forbidden":
        return src
    if not words:
        return None
    match = [v for v in (r.get("variants") or []) if any(w in (v.get("id") or "") for w in words)]
    if match and all(v.get("status") == "forbidden" for v in match):
        return src
    return None


_SWEEP = None


def _style_sweep():
    """{style: front-face svg}: every node with a kit, drawn on the Tidewater plan's placement with
    the style swapped -- the roof sweep's precedent. Ten seconds for 159 elevations."""
    global _SWEEP
    if _SWEEP is not None:
        return _SWEEP
    G, ST, RF, EL, RK = (SURF._mod(n) for n in ("geometry", "structure", "roof", "elevation", "resolve_kit"))
    RE = SURF._mod("render_elevation")
    base = json.load(open(os.path.join(ROOT, "plans", "tidewater-georgian-careful.json")))
    placed = G.solve(base, engine="heuristic")
    g = _graph()
    out = {}
    for sid in sorted(n for n in g["nodes"] if RK.load_kit(n)):
        p = _copy.deepcopy(placed)
        p.setdefault("declared", {})["style"] = sid
        sec = ST.build_section(p, None, geometry_result=p)
        rf = RF.build_roof(p, None, section=sec) if "error" not in sec else {"error": "section"}
        el = EL.build_elevation(p, None, section=sec, roof=rf) if "error" not in rf else rf
        if "error" in el or not el.get("applicable", True):
            out[sid] = None
            continue
        out[sid] = (el, _render(RE.render_elevation, el, face=el["entrance_face"]))
    _SWEEP = out
    return out


@check("V2", "elevation", "nothing the style's resolved kit forbids is drawn, slot or variant (the "
       "row names where each prohibition comes from)", "every node with a kit, on the Tidewater placement")
def v2():
    out = []
    for sid, got in sorted(_style_sweep().items()):
        if got is None:
            out.append(row("V2", sid, "cne", "no elevation drawn for this style"))
            continue
        el, svg = got
        slots = _kit(sid)
        drawn = _drawn_features(svg)
        bad = []
        for name, slot, words in FEATURES:
            if name in drawn:
                src = _forbidden(slots, slot, words)
                if src:
                    bad.append("%s (%s: %s)" % (name, slot, "own" if src == sid else "inherited from " + src))
        out.append(row("V2", sid, "disagrees" if bad else "agrees", "; ".join(bad)))
    return out


@check("V3", "elevation", "every transom or sidelight variant the style's kit makes canonical is "
       "drawn", "every node with a kit, on the Tidewater placement")
def v3():
    out = []
    for sid, got in sorted(_style_sweep().items()):
        if got is None:
            continue
        el, svg = got
        r = _kit(sid).get("transom_sidelight") or {}
        if r.get("binding") == "forbidden":
            continue
        canon = [v["id"] for v in (r.get("variants") or []) if v.get("status") == "canonical" and v.get("id") != "none"]
        if not canon:
            continue
        drawn = _drawn_features(svg)
        missing = [v for v in canon if not ("sidelight" in v and "sidelights" in drawn)]
        out.append(row("V3", sid, "disagrees" if missing else "agrees",
                       ("canonical and not drawn: " + ", ".join(missing)) if missing else ""))
    return out


def _window_boxes(ink):
    """(glass box, [shutter boxes], [vertical muntins], [horizontal muntins]) per window, in px."""
    sh = [_box(r) for r in _rects(ink, "sh")]
    mt = [it for it in ink.select("line", cls="mt") if "w-med" not in it.classes]
    side = {tuple(round(v, 1) for v in _box(r)) for r in _sidelights(ink)}
    out = []
    for r in _rects(ink, "op"):
        b = _box(r)
        if tuple(round(v, 1) for v in b) in side:
            continue
        x0, y0, x1, y1 = b
        leaves = [s for s in sh if (abs(s[2] - x0) < 0.3 or abs(s[0] - x1) < 0.3) and abs(s[1] - y0) < 0.3]
        vert, hor = [], []
        for it in mt:
            (ax, ay), (bx, by) = it.points(n=1)[0], it.points(n=1)[-1]
            if x0 - 0.2 <= ax <= x1 + 0.2 and y0 - 0.2 <= min(ay, by) and max(ay, by) <= y1 + 0.2:
                (vert if abs(ax - bx) < 0.05 else hor).append(it)
        out.append((b, leaves, vert, hor))
    return out


@check("V4", "elevation", "each shutter leaf is (opening - 1 in) / 2, sash-light's own rule, 'so "
       "that the pair actually covers the window when closed'", "elevation sheets drawing shutters")
def v4():
    out = []
    for pid, face, rec, svg in _elev_sheets():
        ink = IR.Ink(svg)
        pl = _face_plate(ink)
        k = pl["px_per_ft"] / 12.0
        wins = [w for w in _window_boxes(ink) if w[1]]
        if not wins:
            continue
        worst = []
        for (x0, y0, x1, y1), leaves, _v, _h in wins:
            want = ((x1 - x0) / k - 1.0) / 2.0
            for s in leaves:
                got = (s[2] - s[0]) / k
                if abs(got - want) > 0.25:
                    worst.append(got / want)
        subject = "%s/%s" % (pid, face)
        if worst:
            out.append(row("V4", subject, "disagrees", "%d leaves off the rule; each is %.0f%%-%.0f%% of "
                           "the leaf its window needs" % (len(worst), 100 * min(worst), 100 * max(worst))))
        else:
            out.append(row("V4", subject, "agrees", "%d windows" % len(wins)))
    return out


def _sash_rule(style, width_in, glass_module_in, which):
    """sash-light's own light count at a width, through the engine (never the renderer)."""
    EL = SURF._mod("elevation")
    PE = SURF._mod("proportion_engine")
    pack = PE.resolve("sash-light")
    v, _r = EL._val(pack, "window_lite_pattern", {"opening_width": width_in, "module": glass_module_in},
                    note_substr=which, dimension="count")
    return None if v is None else int(round(v))


@check("V5", "elevation", "the lights drawn in a sash are sash-light's own count for the width the "
       "window is drawn at", "elevation sheets drawing a glazed sash")
def v5():
    out = []
    for pid, face, rec, svg in _elev_sheets():
        ink = IR.Ink(svg)
        pl = _face_plate(ink)
        k = pl["px_per_ft"] / 12.0
        gm = rec["elev"].get("glass_module_in")
        wins = _window_boxes(ink)
        if not wins or not gm:
            continue
        bad = []
        for (x0, y0, x1, y1), _l, vert, hor in wins:
            w_in = (x1 - x0) / k
            want_a = _sash_rule(None, w_in, gm, "lights across")
            got_a = len({round(it.points(n=1)[0][0], 1) for it in vert}) + 1
            if want_a is not None and got_a != want_a:
                bad.append("%.1f in wide: %d across drawn, the rule gives %d" % (w_in, got_a, want_a))
        subject = "%s/%s" % (pid, face)
        out.append(row("V5", subject, "disagrees" if bad else "agrees",
                       "; ".join(sorted(set(bad))[:3]) if bad else "%d windows" % len(wins)))
    return out


@check("V6", "elevation", "a door the plan calls a garage door is not drawn as a six-panel leaf",
       "plans placing a garage door on an elevation face")
def v6():
    EL = SURF._mod("elevation")
    out = []
    for pid, rec in sorted(_sheets().items()):
        el = rec.get("elev")
        if not el:
            continue
        types = {}
        for lv in rec["placed"].get("levels", []):
            for r in lv["rooms"]:
                for d in r.get("doors", []) or []:
                    if d.get("to") == "exterior" and d.get("type"):
                        types[r["id"]] = d["type"]
        for face, svg in sorted(rec["faces"].items()):
            garage = [x for x in EL.opening_rects(el, face)["rects"]
                      if x["kind"] == "door" and "garage" in str(types.get(x.get("room"), ""))]
            if not garage:
                continue
            ink = IR.Ink(svg)
            pl = _face_plate(ink)
            k = pl["px_per_ft"] / 12.0
            panels = 0
            for x in garage:
                gx0, gx1 = IR.from_model(pl, x["x0_in"] / 12.0, 0)[0], IR.from_model(pl, x["x1_in"] / 12.0, 0)[0]
                panels += sum(1 for r in _rects(ink, "pnl") if gx0 - 0.5 <= _box(r)[0] and _box(r)[2] <= gx1 + 0.5)
            out.append(row("V6", "%s/%s" % (pid, face), "disagrees" if panels else "agrees",
                           ("%d door panels drawn on a garage door %d in wide" % (panels, garage[0]["x1_in"] - garage[0]["x0_in"]))
                           if panels else ""))
    return out


def _elev_and_sweep():
    """The shipped plans' sheets, then every style's front on the Tidewater placement: a head's
    kind and a keystone vary by STYLE, so two plans' sheets reach almost none of them."""
    for pid, face, rec, svg in _elev_sheets():
        yield "%s/%s" % (pid, face), rec["elev"], svg
    for sid, got in sorted(_style_sweep().items()):
        if got:
            yield "style:%s" % sid, got[0], got[1]


@check("V7", "elevation", "an arched head is drawn as the circular segment it is set out as, not a "
       "parabola", "elevation sheets drawing an arched head: shipped plans, and every style's front")
def v7():
    out = []
    for subject, el, svg in _elev_and_sweep():
        ink = IR.Ink(svg)
        heads = ink.select("path", cls="arch")
        if not heads:
            continue
        worst = 0.0
        judged = 0
        for h in heads:
            cmds = h.cmds
            if len(cmds) < 2 or cmds[1][0] not in ("Q", "C", "A"):
                continue
            first = [cmds[0], cmds[1]]
            (pts,) = IR.sample_commands(first, m=h.ctm, n=32)
            try:
                cx, cy, r, _rms = IR.fit_circle(pts)
            except ValueError:
                continue                      # a straight soffit: nothing to judge
            judged += 1
            worst = max(worst, max(abs(((x - cx) ** 2 + (y - cy) ** 2) ** 0.5 - r) for x, y in pts))
        if not judged:
            continue
        # half the print quantum: a departure below 0.05 px cannot be seen or measured on the sheet
        if worst > 0.05:
            out.append(row("V7", subject, "disagrees", "%d heads; the drawn soffit departs from a circle "
                           "by up to %.2f px" % (judged, worst)))
        else:
            out.append(row("V7", subject, "agrees", "%d heads" % judged))
    return out


# (measurement, pack, slot, dimension): figures the elevation publishes that a rule states. The
# rule's own `judgment` flag is read from the pack every run, so the row follows the record.
JUDGED_MEASUREMENTS = (
    ("transom_height_in", "opening-proportion", "transom_sidelight", "height"),
    ("pilaster_projection_in", "gibbs-ionic", "pilaster", "projection"),
)


@check("V8", "elevation", "a figure its own rule marks judgment is not published as a measurement",
       "plans whose elevation draws")
def v8():
    PE = SURF._mod("proportion_engine")
    out = []
    for pid, rec in sorted(_sheets().items()):
        el = rec.get("elev")
        if not el:
            continue
        m = el.get("measurements") or {}
        bad = []
        for name, pack, slot, dim in JUDGED_MEASUREMENTS:
            rule = next((r for r in (PE.resolve(pack).get("derived_rules") or [])
                         if r.get("target_slot") == slot and r.get("dimension") == dim), None)
            if rule and rule.get("judgment") and m.get(name) is not None:
                bad.append("%s = %s (%s %s/%s is judgment)" % (name, m[name], pack, slot, dim))
        out.append(row("V8", pid, "disagrees" if bad else "agrees", "; ".join(bad)))
    return out


@check("V9", "elevation", "a size drawn with no figure behind it is said: the keystone's depth x 0.6 "
       "and the chimney's 22 in fallback", "sheets drawing a keystone or a chimney: shipped plans, and every style's front")
def v9():
    out = []
    for subject, el, svg in _elev_and_sweep():
        ink = IR.Ink(svg)
        said = " ".join(t for t, _a, _it in ink.texts()).upper()
        bad = []
        heads = [sw.get("head_treatment") or {} for sw in el.get("storey_windows") or []]
        if _rects(ink, "arch") and any(h.get("keystone") and not h.get("keystone_width_in") for h in heads):
            if "KEYSTONE" not in said:
                bad.append("a keystone drawn at 0.6 x the arch depth, which no record states, and not said")
        if _rects(ink, "ch") and not el.get("chimney_stack_plan_in"):
            bad.append("a stack drawn at 22 in square with no figure behind it, and not said")
        if not (_rects(ink, "arch") or _rects(ink, "ch")):
            continue
        out.append(row("V9", subject, "disagrees" if bad else "agrees", "; ".join(bad)))
    return out


@check("V11", "elevation", "an opening or a belt that misses the brick courses the sheet draws is "
       "said to", "masonry elevation sheets")
def v11():
    out = []
    for pid, face, rec, svg in _elev_sheets():
        el = rec["elev"]
        wtb = el.get("water_table_belt") or {}
        c = wtb.get("course_height_in")
        if not c or not wtb.get("applicable"):
            continue
        ink = IR.Ink(svg)
        pl = _face_plate(ink)
        courses = sorted(IR.to_model(pl, *it.points(n=1)[0])[1] * 12.0 for it in ink.select("line", cls="course"))
        if not courses:
            continue
        miss = 0
        judged = 0
        for r in _rects(ink, "op"):
            x0, y0, x1, y1 = _box(r)
            for ypx in (y0, y1):
                v = IR.to_model(pl, x0, ypx)[1] * 12.0
                if v < courses[0] or v > courses[-1]:
                    continue
                judged += 1
                if min(abs(v - cv) for cv in courses) > 0.05:
                    miss += 1
        if not judged:
            continue
        said = "COURSE" in " ".join(t for t, _a, _it in ink.texts()).upper()
        subject = "%s/%s" % (pid, face)
        if miss and not said:
            out.append(row("V11", subject, "disagrees", "%d of %d sill and head lines miss the %.2f in courses "
                           "drawn behind them, unsaid" % (miss, judged, c)))
        else:
            out.append(row("V11", subject, "agrees", "%d of %d miss%s" % (miss, judged, ", said" if miss else "")))
    return out


@check("V13", "elevation", "the eave inset draws every cornice member at the height and face its "
       "record states", "elevation sheets drawing the eave inset")
def v13():
    PROF = SURF._mod("profiles")
    out = []
    for pid, face, rec, svg in _elev_sheets():
        if face != rec["elev"].get("entrance_face"):
            continue
        ink = IR.Ink(svg)
        inset = next((p for p in ink.frames() if p.get("id") == "inset"), None)
        if inset is None:
            out.append(row("V13", pid, "cne", "the sheet states no frame for its inset"))
            continue
        fills = [it for it in ink.select("path") if (it.style.get("fill") or "none") not in ("none",)
                 and not it.classes]
        if len(fills) != 1:
            out.append(row("V13", pid, "cne", "%d unclassed filled paths where one profile was expected" % len(fills)))
            continue
        pts = [IR.to_model(inset, x, y) for sub in fills[0].subpaths(n=48, lines=True) for x, y in sub]
        cor = rec["elev"]["eave_cornice"]
        members = cor["members"]
        naked = inset["at_origin_in"][0]
        axis = inset.get("datum") == "axis"
        bad = []
        want_h = max(m["y_top_in"] for m in members)
        got_h = max(v for u, v in pts) - min(v for u, v in pts)
        if abs(got_h - want_h) > 0.02:
            bad.append("drawn %.2f in high against %.2f" % (got_h, want_h))
        for m in members:
            if (m.get("profile") or "flat") not in SURF.FACE_AT_MID:
                continue
            want = PROF.outer_face(naked, m.get("projection_in") or 0.0, axis)
            vm = (m["y_bottom_in"] + m["y_top_in"]) / 2.0
            xs = []
            for sub in fills[0].subpaths(n=64, lines=True):
                q = [IR.to_model(inset, x, y) for x, y in sub]
                for (u0, v0), (u1, v1) in zip(q, q[1:]):
                    if (v0 - vm) * (v1 - vm) <= 0 and v0 != v1:
                        xs.append(u0 + (u1 - u0) * (vm - v0) / (v1 - v0))
            got = max(xs) if xs else None
            if got is None or abs(got - want) > 0.02:
                bad.append("%s drawn to %s, record %.2f" % (m["id"], "nothing" if got is None else "%.2f" % got, want))
        out.append(row("V13", pid, "disagrees" if bad else "agrees", "; ".join(bad[:4])))
    return out


@check("S1", "section", "exterior walls are drawn as bodies of the thickness the record states",
       "plans whose section draws")
def s1():
    out = []
    for pid, rec in sorted(_sheets().items()):
        svg = rec.get("sec_svg")
        if not svg:
            continue
        t = ((rec["section"].get("wall") or {}).get("exterior_in"))
        ink = IR.Ink(svg)
        pl = next((p for p in ink.frames() if p.get("proj") == "section"), None)
        eave = rec["section"]["roof"]["grade_to_eave_ft"]
        span = min(rec["section"]["footprint"]["width_ft"], rec["section"]["footprint"]["depth_ft"])
        # A WALL BODY is a CLOSED shape about as wide as the stated wall, standing from grade most of
        # the way to the eave, at either end of the span. The first version counted any `wl` path,
        # and the roof's own eave-to-ridge line is a `wl` path: three plans read as walls drawn.
        bodies = {}
        for it in ink.items:
            closed = it.tag in ("rect", "polygon") or (it.tag == "path" and any(c[0] == "Z" for c in it.cmds or []))
            if not closed or not it.cmds:
                continue
            (x0, y0), (x1, y1) = [IR.to_model(pl, *xy) for xy in ((it.bbox()[0], it.bbox()[3]), (it.bbox()[2], it.bbox()[1]))]
            w_in, h_ft = (x1 - x0) * 12.0, y1 - y0
            if t and abs(w_in - t) <= 0.25 * t and y0 <= 0.5 and h_ft >= 0.5 * eave:
                side = "left" if abs(x0) < 1.5 or abs(x1) < 1.5 else ("right" if abs(x0 - span) < 1.5 or abs(x1 - span) < 1.5 else None)
                if side:
                    bodies[side] = w_in
        walls = [it for it in ink.items if "wl" in it.classes and it.tag == "line"]
        if not t:
            out.append(row("S1", pid, "cne", "the record states no exterior wall thickness"))
        elif len(bodies) < 2:
            out.append(row("S1", pid, "disagrees", "the record states %.1f in; %s drawn as a body, and the "
                           "envelope is %d lines of no thickness" % (t, ", ".join(sorted(bodies)) or "neither wall",
                                                                      len(walls))))
        else:
            out.append(row("S1", pid, "agrees"))
    return out


@check("F1", "roof", "a chimney stack is drawn at the plan size the record states, and a judged "
       "size is said to be one", "plans whose roof plan draws a stack")
def f1():
    out = []
    for pid, rec in sorted(_sheets().items()):
        svg = rec.get("roof_svg")
        if not svg:
            continue
        ink = IR.Ink(svg)
        pl = next((p for p in ink.frames() if p.get("proj") == "roof"), None)
        stacks = [it for it in ink.items if "chm" in it.classes]
        if not stacks:
            continue
        size = (rec.get("elev") or {}).get("chimney_stack_plan_in")
        drawn = [(b[2] - b[0]) / pl["px_per_ft"] * 12.0 for b in (it.bbox() for it in stacks)]
        if not size:
            out.append(row("F1", pid, "cne", "%d stacks drawn and the record states no plan size" % len(stacks)))
        elif any(abs(d - size) > 0.5 for d in drawn):
            out.append(row("F1", pid, "disagrees", "%d stacks drawn %.1f in across; the record states %.0f in"
                           % (len(stacks), drawn[0], size)))
        else:
            out.append(row("F1", pid, "agrees"))
    return out


@check("X1", "elevation", "the DXF elevation draws the sidelights the SVG draws beside the doorcase",
       "plans whose entrance SVG draws sidelights")
def x1():
    try:
        import ezdxf  # noqa: F401
    except ImportError:
        return [row("X1", "export_dxf", "cne", "ezdxf is not installed, so the DXF cannot be drawn")]
    DX = SURF._mod("export_dxf")
    out = []
    for pid, rec in sorted(_sheets().items()):
        el = rec.get("elev")
        if not el:
            continue
        face = el["entrance_face"]
        svg_side = len(_sidelights(IR.Ink(rec["faces"][face])))
        if not svg_side:
            continue
        d = _tempfile.mkdtemp(prefix="svg_census_")
        try:
            path = os.path.join(d, "e.dxf")
            DX.export_elevation_dxf(el, path, face=face)
            doc = ezdxf.readfile(path)
            boxes = []
            for e in doc.modelspace().query("LWPOLYLINE"):
                xs = [p[0] for p in e.get_points()]
                ys = [p[1] for p in e.get_points()]
                boxes.append((min(xs), min(ys), max(xs), max(ys), e.dxf.layer))
        finally:
            shutil.rmtree(d, ignore_errors=True)
        ent = next((r for r in SURF._mod("elevation").opening_rects(el, face)["rects"] if r.get("entrance")), None)
        cw = el["entrance"]["casing_width_in"]
        cx0, cx1 = ent["x0_in"] - cw, ent["x1_in"] + cw
        dxf_side = sum(1 for b in boxes if abs(b[2] - cx0) < 0.05 or abs(b[0] - cx1) < 0.05)
        out.append(row("X1", pid, "agrees" if dxf_side == svg_side else "disagrees",
                       "" if dxf_side == svg_side else "the SVG draws %d sidelights, the DXF %d" % (svg_side, dxf_side)))
    return out


@check("PL1", "plan", "a bay grid is drawn on a module the record states, or the sheet says the "
       "module is a default", "every plan sheet, working register")
def pl1():
    G = SURF._mod("geometry")
    out = []
    for pid, rec in sorted(_sheets().items()):
        parti = G.parti_for(rec["plan"], None)
        stated = ((parti or {}).get("scaling") or {}).get("bay_module_ft")
        fp = rec["placed"].get("footprint") or {}
        # the WORKING register: `render()`'s default, and the one that draws the bay grid (the
        # presentation register draws none, so reading it here judged nothing on 15 plans)
        svg = rec["plan_svg_working"]
        ink = IR.Ink(svg)
        grid = [it for it in ink.items if "gd" in it.classes]
        # ONE SENTENCE that is about the bay module and says it was not stated. The first version
        # searched the whole sheet for DEFAULT or ASSUMED and was satisfied by "NO CONSTRUCTION_TYPE
        # DECLARED ON THIS PLAN; ASSUMED PLATFORM-FRAME" -- a true sentence about the walls, read as
        # a disclosure about the grid.
        said = any(re.search(r"\bBAYS?\b.*\b(DEFAULT|ASSUMED|NOT STATED)|\b(DEFAULT|ASSUMED|NOT STATED)\b.*\bBAYS?\b",
                             (t or "").upper()) for t, _a, _it in ink.texts())
        if stated:
            out.append(row("PL1", pid, "agrees", "%g ft, from the parti" % stated))
        elif grid and not said:
            out.append(row("PL1", pid, "disagrees", "a %g ft grid of %d lines drawn and labelled; no parti "
                           "states a module and the sheet does not say it is the placer's default"
                           % (fp.get("bay_module_ft") or 0, len(grid))))
        else:
            out.append(row("PL1", pid, "agrees"))
    return out


# ------------------------------------------------------------------ running it
def run(only=None):
    rows = []
    for cid, c in CHECKS.items():
        if only and c["surface"] not in only and cid not in only:
            continue
        rows.extend(c["fn"]())
    return rows


def summary(rows):
    out = {}
    for cid, c in CHECKS.items():
        rs = [r for r in rows if r["check"] == cid]
        if not rs and cid not in {r["check"] for r in rows}:
            pass
        out[cid] = {"surface": c["surface"], "statement": c["statement"], "population": c["population"],
                    "rows": len(rs), "agrees": sum(r["verdict"] == "agrees" for r in rs),
                    "disagrees": sum(r["verdict"] == "disagrees" for r in rs),
                    "cne": sum(r["verdict"] == "cne" for r in rs)}
    return out


def disagreement_ids(rows):
    return sorted("%s:%s" % (r["check"], r["subject"]) for r in rows if r["verdict"] == "disagrees")


def disagreements(rows):
    """{id: detail} for every row that disagrees. THE DETAIL IS PINNED WITH THE ID, and the reason
    is measured: with ids alone, corrupting V1's own rung table and making V5 count the wrong
    muntins both left the build green -- every V1 and V5 row already disagreed, so a change in
    WHAT a row reports was invisible. A row red for one cause cannot report a second unless its
    figures are held as well as its verdict."""
    return {"%s:%s" % (r["check"], r["subject"]): r["detail"] for r in rows if r["verdict"] == "disagrees"}


def render_doc_tables(rows):
    s = summary(rows)
    lines = ["| check | surface | statement | population | rows | agrees | disagrees | could not evaluate |",
             "|---|---|---|---|---:|---:|---:|---:|"]
    for cid, x in s.items():
        lines.append("| %s | %s | %s | %s | %d | %d | %d | %d |" % (
            cid, x["surface"], x["statement"], x["population"], x["rows"], x["agrees"],
            x["disagrees"], x["cne"]))
    reg = ["| id | role | file | surface / reason |", "|---|---|---|---|"]
    for r in REGISTRY:
        reg.append("| %s | %s | `%s` | %s |" % (r["id"], r["role"], r["file"],
                                                r.get("surface") or r.get("reason")))
    return "\n".join(reg), "\n".join(lines)


_MARK = ("<!-- census:%s:begin -->", "<!-- census:%s:end -->")


def splice(text, name, body):
    b, e = _MARK[0] % name, _MARK[1] % name
    i, j = text.index(b) + len(b), text.index(e)
    return text[:i] + "\n" + body + "\n" + text[j:]


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--write-doc", action="store_true")
    ap.add_argument("--surface", action="append")
    ap.add_argument("--diff", action="store_true",
                    help="what moved against tests/fixtures/ink_known_disagreements.json")
    ap.add_argument("--pin", action="store_true",
                    help="rewrite the known disagreements to the live census (say why in the commit)")
    a = ap.parse_args()
    rows = run(set(a.surface) if a.surface else None)
    if a.diff or a.pin:
        if a.surface:
            ap.error("--diff and --pin read the WHOLE census: a partial run would call every "
                     "unrun row fixed")
        doc = json.load(open(KNOWN))
        known, live = doc["disagreements"], disagreements(rows)
        new = sorted(set(live) - set(known))
        fixed = sorted(set(known) - set(live))
        moved = sorted(k for k in set(known) & set(live) if known[k] != live[k])
        for label, ids in (("NEW", new), ("FIXED", fixed), ("MOVED", moved)):
            print("%s %d" % (label, len(ids)))
            for k in ids:
                print("   %s  %s" % (k, live.get(k, known.get(k)) if label != "MOVED"
                                     else "%r -> %r" % (known[k], live[k])))
        if a.pin:
            doc["disagreements"] = {k: live[k] for k in sorted(live)}
            with open(KNOWN, "w", encoding="utf-8") as fh:
                json.dump(doc, fh, indent=1, ensure_ascii=False)
                fh.write("\n")
            print("pinned", len(live))
        return 0
    if a.json:
        print(json.dumps({"summary": summary(rows), "rows": rows}, indent=1))
        return 0
    if a.write_doc:
        reg, table = render_doc_tables(rows)
        text = open(DOC).read()
        text = splice(splice(text, "registry", reg), "checks", table)
        open(DOC, "w").write(text)
        print("wrote", os.path.relpath(DOC, ROOT))
        return 0
    for cid, x in summary(rows).items():
        print("%-4s %-18s agrees %4d  disagrees %4d  cne %4d   %s"
              % (cid, x["surface"], x["agrees"], x["disagrees"], x["cne"], x["statement"]))
    print("\nunregistered SVG emitters:", unregistered() or "none")
    return 0


if __name__ == "__main__":
    sys.exit(main())
