#!/usr/bin/env python3
"""svg_census.py — every SVG this app draws, and whether its ink agrees with its record (WP-14.1).

    python3 tests/svg_census.py              # the summary table
    python3 tests/svg_census.py --json       # every row, machine-readable
    python3 tests/svg_census.py --write-doc  # regenerate the tables in docs/fidelity.md

WHY A CENSUS AND NOT A TEST FILE. Lucas asked for "all areas of the app that generate SVGs ...
every surface covered", and a claim about ALL surfaces is only as good as the list it is made
over. So the list is data here -- `REGISTRY` -- and `tests/test_svg_census.py` greps the tree for
anything that emits SVG and fails on a file the registry does not name. A new surface cannot
join the app without either a row here or a stated reason it is out of scope.

EVERY CHECK HAS THREE ANSWERS: agrees, disagrees (with the figures), COULD NOT EVALUATE (with the
reason). A check that finds nothing to evaluate is a check that evaluated nothing; its
population is printed beside its verdicts so a zero reads as a zero and not as a pass.

THE KNOWN DISAGREEMENTS ARE HELD BY IDENTITY. `tests/fixtures/ink_known_disagreements.json`
names every row that disagrees today, and the test holds the live set EQUAL to it: a new
disagreement fails, and a fixed one must be removed from the file. That is the one-way door
`build/measured_unsourced_grandfathered.json` already uses, chosen over `xfail` and over a red
build because a suite already red for one cause cannot report a second.
"""
import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, "build"))

import ink_surfaces as SURF  # noqa: E402

DOC = os.path.join(ROOT, "docs", "fidelity.md")
KNOWN = os.path.join(HERE, "fixtures", "ink_known_disagreements.json")

# ------------------------------------------------------------------ the registry
# role: "producer" draws architectural SVG; "carrier" moves another producer's SVG to a reader
# without drawing; "helper" builds path data a producer emits; "out-of-scope" is not an
# architectural drawing and is listed so the claim "every surface" is checkable.
REGISTRY = [
    {"id": "profile-plates", "file": "build/render_profile.py", "role": "producer",
     "surface": "73 moulding-profile plates committed under assets/generated/",
     "served": "/corpus/assets/generated/*.svg, tdl_find_assets, /api/assets"},
    {"id": "orders-tool", "file": "build/orders_template.html", "role": "producer",
     "surface": "the order-drawing tool dist/orders.html (half section, mirrored elevation)",
     "served": "dist/orders.html (generated by build/render_orders.py)"},
    {"id": "proportions-plate", "file": "workbench/app/src/surfaces/Proportions.jsx", "role": "producer",
     "surface": "the workbench Proportions plate (half section of each order pack)",
     "served": "workbench surface; paths from corpus.proportions_with_members"},
    {"id": "elevation", "file": "build/render_elevation.py", "role": "producer",
     "surface": "elevation sheets, each with an eave-cornice profile inset",
     "served": "POST /api/drawings/elevation, the Drawing Set, the Round"},
    {"id": "section", "file": "build/render_section.py", "role": "producer",
     "surface": "the building section and the bearing diagram",
     "served": "POST /api/drawings/section and /bearing"},
    {"id": "roof", "file": "build/render_roof.py", "role": "producer",
     "surface": "the roof plan", "served": "POST /api/drawings/roof"},
    {"id": "plan", "file": "build/render_plan.py", "role": "producer",
     "surface": "the plan sheet (presentation and working registers)",
     "served": "POST /api/drawings/plan, tdl_place_plan, the Drawing Set"},
    {"id": "bench-sheet", "file": "workbench/app/src/sheet/Sheet.jsx", "role": "producer",
     "surface": "the Plan Workbench's live sheet, drawn in JavaScript",
     "served": "workbench surface"},
    {"id": "transcription", "file": "workbench/app/src/surfaces/Transcription.jsx", "role": "producer",
     "surface": "the Transcription draft canvas (a person's own tracing)",
     "served": "workbench surface"},
    {"id": "profiles-geometry", "file": "build/profiles.py", "role": "helper",
     "surface": "the moulding constructions and their SVG path serialiser",
     "served": "used by the profile plates, the orders tool, the Proportions plate, the elevation inset"},
    {"id": "drawing-set", "file": "workbench/app/src/surfaces/DrawingSet.jsx", "role": "carrier",
     "surface": "injects the server's plan/elevation/section/roof SVG; offers it for download",
     "served": "workbench surface"},
    {"id": "export-details", "file": "workbench/app/src/surfaces/ExportDetails.jsx", "role": "carrier",
     "surface": "downloads the server's presentation-register SVG", "served": "workbench surface"},
    {"id": "round-plates", "file": "workbench/app/src/round/RoundPlate.jsx", "role": "carrier",
     "surface": "lays the Python plates over the 3D model by their data-frame",
     "served": "workbench surface"},
    {"id": "taxonomy-timeline", "file": "build/template.html", "role": "out-of-scope",
     "reason": "the taxonomy page's timeline and ruler: a chart of dates, not a drawing of a building"},
    {"id": "phylogeny", "file": "workbench/app/src/surfaces/Phylogeny.jsx", "role": "out-of-scope",
     "reason": "the lineage graph: a diagram of influence between styles"},
    {"id": "atlas", "file": "workbench/app/src/surfaces/phylo/MapView.jsx", "role": "out-of-scope",
     "reason": "the atlas: coastlines and a graticule, not architecture"},
    {"id": "tokens", "file": "workbench/app/src/theme/tokens.css", "role": "out-of-scope",
     "reason": "a stylesheet that names <svg> in a comment; it draws nothing"},
]

# WHAT COUNTS AS EMITTING SVG. The first version matched `<svg` alone and was blind to a React
# component that returns a `<path>` or a `<line>` inside its parent's `<svg>` -- it never writes
# the root element, and it is exactly where a second spelling of a mark would grow. So a primitive
# counts too, but only followed by an ATTRIBUTE: `<path>[]` in a docstring and `(?P<path>` in a
# route regex are prose and code, not ink. A carrier that injects a server's SVG is found by
# `dangerouslySetInnerHTML`, because it writes no primitive of its own.
_EMIT = re.compile(r"<(svg|path|polyline|polygon|circle|ellipse|line|rect)\s+[a-zA-Z]|"
                   r"createElementNS|image/svg\+xml|dangerouslySetInnerHTML")
_SKIP = re.compile(r"^(tests/|docs/|dist/|assets/|workbench/app/e2e/|workbench/server/tests/|"
                   r"workbench/app/dist/)|node_modules|\.(md|json|svg|txt|b64)$|\.test\.m?js$")


def emitters(root=ROOT):
    """Every tracked or new file (never a walk: WP-13.2's rule) that mentions an SVG emitter."""
    files = subprocess.run(["git", "ls-files", "-co", "--exclude-standard"], cwd=root,
                           capture_output=True, text=True, check=True).stdout.split()
    out = []
    for f in sorted(files):
        if _SKIP.search(f):
            continue
        try:
            with open(os.path.join(root, f), encoding="utf-8", errors="ignore") as fh:
                if _EMIT.search(fh.read()):
                    out.append(f)
        except (IsADirectoryError, FileNotFoundError):
            continue
    return out


def unregistered(root=ROOT):
    named = {r["file"] for r in REGISTRY}
    return [f for f in emitters(root) if f not in named]


# ------------------------------------------------------------------ the checks
CHECKS = {}


def check(cid, surface, statement, population):
    def wrap(fn):
        CHECKS[cid] = {"id": cid, "surface": surface, "statement": statement,
                       "population": population, "fn": fn}
        return fn
    return wrap


def row(cid, subject, verdict, detail=""):
    assert verdict in ("agrees", "disagrees", "cne"), verdict
    return {"check": cid, "subject": subject, "verdict": verdict, "detail": detail}


_PLATES = None


def _profile_assets():
    """The committed plates, read back from the files a reader is served."""
    global _PLATES
    if _PLATES is None:
        doc = json.load(open(os.path.join(ROOT, "assets", "manifest.json")))
        _PLATES = []
        for a in doc["assets"]:
            g = a.get("generated_from")
            if not g:
                continue
            path = os.path.join(ROOT, a["file"]["path"])
            svg = open(path).read()
            _PLATES.append((a, g, SURF.ProfilePlate(svg),
                            SURF.profile_record(g["pack"], (g.get("parameters") or {}).get("assembly"),
                                                g.get("module_in") or 6.0)))
    return _PLATES


def _unreadable(pl):
    """Why this plate's geometry cannot be read back, or None. A plate that states no frame, or
    whose silhouette is not one filled path, is COULD NOT EVALUATE with that reason -- never a
    crash, which would stop every later check, and never a pass."""
    if pl.plate is None:
        return "the plate states no data-frame, so its pixels cannot be read as inches"
    if pl.outline is None:
        return "%d filled paths where one silhouette was expected" % pl.n_outlines
    return None


def _fig(pattern, text):
    m = re.search(pattern, text)
    return float(m.group(1)) if m else None


@check("P1", "profile-plates", "the column diameter a plate prints is the diameter it is drawn at",
       "every committed profile plate")
def p1():
    out = []
    for a, g, pl, rec in _profile_assets():
        got = _fig(r"at a ([\d.]+)″ column", pl.flat_text)
        want = rec["lower_diameter_in"]
        if got is None:
            out.append(row("P1", a["id"], "cne", "no column diameter printed"))
        elif abs(got - want) > 0.5:
            out.append(row("P1", a["id"], "disagrees", "prints %g in, drawn at %g in" % (got, want)))
        else:
            out.append(row("P1", a["id"], "agrees"))
    return out


@check("P2", "profile-plates", "the relief a plate prints is the relief its ink draws",
       "every committed profile plate")
def p2():
    out = []
    for a, g, pl, rec in _profile_assets():
        got = _fig(r"([\d.]+)″ of relief", pl.flat_text)
        why = _unreadable(pl) or (None if got is not None else "no relief printed")
        if why:
            out.append(row("P2", a["id"], "cne", why))
            continue
        drawn = max(u for u, v in pl.points()) - pl.naked()
        if abs(got - drawn) > 0.011:
            out.append(row("P2", a["id"], "disagrees", "prints %.2f in, draws %.2f in" % (got, drawn)))
        else:
            out.append(row("P2", a["id"], "agrees"))
    return out


@check("P3", "profile-plates", "no ink falls inside the assembly's own naked (a moulding bitten "
       "into the member it stands on)", "every committed profile plate")
def p3():
    out = []
    for a, g, pl, rec in _profile_assets():
        if _unreadable(pl):
            out.append(row("P3", a["id"], "cne", _unreadable(pl)))
            continue
        worst = pl.naked() - min(u for u, v in pl.points())
        if worst > 0.01:
            out.append(row("P3", a["id"], "disagrees", "ink %.2f in inside the naked" % worst))
        else:
            out.append(row("P3", a["id"], "agrees"))
    return out


@check("P4", "profile-plates", "every mark of ink is inside the plate's viewBox",
       "every committed profile plate")
def p4():
    out = []
    for a, g, pl, rec in _profile_assets():
        x0, y0, w, h = pl.ink.viewbox()
        bad = 0
        for it in pl.ink.items:
            if it.tag == "text" or not it.cmds:
                continue
            for x, y in it.points(n=24):
                if x < x0 - 0.5 or y < y0 - 0.5 or x > x0 + w + 0.5 or y > y0 + h + 0.5:
                    bad += 1
        out.append(row("P4", a["id"], "disagrees" if bad else "agrees",
                       ("%d sampled point(s) outside the viewBox" % bad) if bad else ""))
    return out


@check("P5", "profile-plates", "every member boundary the record states is a drawn vertex, and "
       "the drawn height is the stated height", "every committed profile plate")
def p5():
    out = []
    for a, g, pl, rec in _profile_assets():
        if _unreadable(pl):
            out.append(row("P5", a["id"], "cne", _unreadable(pl)))
            continue
        vs = sorted({round(p[1][1], 4) for p in pl.segments_in_model()} |
                    {round(p[2][1], 4) for p in pl.segments_in_model()})
        missing = []
        for m in rec["members"]:
            if rec["side_by_side"]:
                continue
            for b in (m["y_bottom_in"], m["y_top_in"]):
                if not any(abs(b - v) <= 0.01 for v in vs):
                    missing.append("%s@%.3f" % (m["id"], b))
        pts = pl.points()
        span = max(v for u, v in pts) - min(v for u, v in pts)
        want = max(m["y_top_in"] for m in rec["members"]) - min(m["y_bottom_in"] for m in rec["members"])
        if missing or abs(span - want) > 0.01:
            out.append(row("P5", a["id"], "disagrees",
                           "drawn %.3f in against %.3f; boundaries not drawn: %s"
                           % (span, want, ", ".join(sorted(set(missing))[:6]) or "none")))
        else:
            out.append(row("P5", a["id"], "agrees"))
    return out


@check("P6", "profile-plates", "a member whose face is at its mid-height (a step or a half round) "
       "is drawn out to the face its record states", "members with a published projection")
def p6():
    out = []
    PROF = SURF._mod("profiles")
    for a, g, pl, rec in _profile_assets():
        if _unreadable(pl):
            out.append(row("P6", a["id"], "cne", _unreadable(pl)))
            continue
        naked = pl.naked()
        datum = pl.plate.get("datum")
        bad = []
        judged = 0
        for m in rec["members"]:
            if rec["side_by_side"] or not rec["published"].get(m["id"]):
                continue
            if (m.get("profile") or "flat") not in SURF.FACE_AT_MID:
                continue
            want = PROF.outer_face(naked, m.get("projection_in") or 0.0, datum == "axis")
            got = pl.extent_at((m["y_bottom_in"] + m["y_top_in"]) / 2.0)
            judged += 1
            if got is None or abs(got - want) > 0.02:
                bad.append("%s drawn to %s, record %.3f" % (m["id"], "nothing" if got is None else "%.3f" % got, want))
        if not judged:
            out.append(row("P6", a["id"], "cne", "no member of a kind this check reads"))
        elif bad:
            out.append(row("P6", a["id"], "disagrees", "; ".join(bad[:4])))
        else:
            out.append(row("P6", a["id"], "agrees", "%d member(s)" % judged))
    return out


@check("P7", "profile-plates", "a member the record gives no projection for is SAID to have "
       "none, not drawn as though measured flush", "plates holding an unpublished member")
def p7():
    out = []
    for a, g, pl, rec in _profile_assets():
        n = sum(1 for m in rec["members"] if not rec["published"].get(m["id"]))
        if not n:
            continue
        said = re.search(r"(\d+) MEMBER\(S\)[^.]*NO PROJECTION PUBLISHED", pl.flat_text.upper())
        if said and int(said.group(1)) == n:
            out.append(row("P7", a["id"], "agrees", "%d unpublished, said" % n))
        else:
            out.append(row("P7", a["id"], "disagrees",
                           "%d member(s) carry no projection in the record; the plate %s"
                           % (n, "says %s" % said.group(1) if said else "says nothing")))
    return out


@check("P8", "profile-plates", "a member the plate calls NOT CONSTRUCTED has no curve drawn "
       "for it", "plates holding a volute or acanthus member")
def p8():
    out = []
    for a, g, pl, rec in _profile_assets():
        unc = [m for m in rec["members"] if (m.get("profile") or "") in SURF.UNCONSTRUCTED]
        if not unc:
            continue
        if _unreadable(pl):
            out.append(row("P8", a["id"], "cne", _unreadable(pl)))
            continue
        curved = sum(len(pl.segments_within(m["y_bottom_in"], m["y_top_in"])) for m in unc)
        if curved:
            out.append(row("P8", a["id"], "disagrees",
                           "%d curve(s) inked for %d member(s) the plate says are not constructed"
                           % (curved, len(unc))))
        else:
            out.append(row("P8", a["id"], "agrees"))
    return out


@check("P9", "profile-plates", "a plate showing another authority's members says whose they are",
       "every committed profile plate")
def p9():
    out = []
    for a, g, pl, rec in _profile_assets():
        pack = g["pack"]
        owner = rec["owner"]
        says = "INHERITED" in pl.flat_text
        names = owner and owner in pl.flat_text
        if owner and owner != pack:
            ok = says and names
        else:
            ok = not says
        out.append(row("P9", a["id"], "agrees" if ok else "disagrees",
                       "" if ok else "owner %s; plate %s INHERITED" % (owner, "says" if says else "does not say")))
    return out


@check("P10", "profile-plates", "a member whose record confidence is not high is marked as such "
       "on the plate", "plates holding a medium- or low-confidence member")
def p10():
    out = []
    for a, g, pl, rec in _profile_assets():
        # an UNSTATED confidence is not a high one; every member states one today (733 of 733)
        weak = [m for m in rec["members"]
                if (rec["raw"].get(m["id"], {}).get("confidence") or "unstated") != "high"]
        if not weak:
            continue
        marked = len(re.findall(r"\b(?:LOW|MEDIUM) CONFIDENCE\b", pl.flat_text.upper()))
        # every weak member carries its mark in its own label, so the count must match
        if marked >= len(weak):
            out.append(row("P10", a["id"], "agrees", "%d marked" % len(weak)))
        else:
            out.append(row("P10", a["id"], "disagrees",
                           "%d of %d member(s) are medium or low confidence; %d marked"
                           % (len(weak), len(rec["members"]), marked)))
    return out


@check("P11", "profile-plates", "a curved member drawn as a straight line says so",
       "plates holding a curved profile kind")
def p11():
    out = []
    for a, g, pl, rec in _profile_assets():
        curved = [m for m in rec["members"] if (m.get("profile") or "") in SURF.CURVED
                  and not rec["side_by_side"]]
        if not curved:
            continue
        if _unreadable(pl):
            out.append(row("P11", a["id"], "cne", _unreadable(pl)))
            continue
        straight = [m["id"] for m in curved
                    if not pl.segments_within(m["y_bottom_in"], m["y_top_in"])]
        if not straight:
            out.append(row("P11", a["id"], "agrees"))
            continue
        said = re.search(r"(\d+) CURVED MEMBER\(S\) DRAWN STRAIGHT", pl.flat_text.upper())
        if said and int(said.group(1)) == len(straight):
            out.append(row("P11", a["id"], "agrees", "%d straight, said" % len(straight)))
        else:
            out.append(row("P11", a["id"], "disagrees",
                           "%s drawn straight and not said" % ", ".join(straight[:5])))
    return out


@check("P12", "profile-plates", "the committed plate is the renderer's current output",
       "every committed profile plate")
def p12():
    RP = SURF._mod("render_profile")
    out = []
    for a, g, pl, rec in _profile_assets():
        svg, _rep = RP.render(g["pack"], (g.get("parameters") or {}).get("assembly"),
                              module_in=g.get("module_in") or 6.0)
        out.append(row("P12", a["id"], "agrees" if svg + "\n" == pl.svg else "disagrees",
                       "" if svg + "\n" == pl.svg else "stale: re-run build/render_profile.py --write"))
    return out


# ------------------------------------------------------------------ the order stack (link 2)
# The orders tool and the Proportions plate draw a WHOLE column and entablature, stacked by the
# engine's `stack_for` and dimensioned by `dimension()` -- the orders page through a JavaScript
# port of both. These checks hold that stack to what each pack STATES, before any ink: a column
# drawn at the wrong height is wrong on every surface that draws it, and asking each surface
# separately would report one defect three times.
def _order_packs():
    PE = SURF._mod("proportion_engine")
    for pid in sorted(PE.PACKS):
        if (PE.PACKS[pid].get("kind") or "") != "order-system":
            continue
        pack = PE.resolve(pid)
        dim = PE.dimension(pack, module_in=6.0)
        heights = {a["id"]: a["y_top_in"] - a["y_bottom_in"] for a in dim["assemblies"]}
        yield pid, pack, dim, heights


@check("E1", "order-stack", "the column drawn (base + shaft + capital) is the column height the "
       "pack states", "order packs stating a column height")
def e1():
    out = []
    for pid, pack, dim, H in _order_packs():
        col = dim["totals"].get("column_height_in")
        if not col:
            continue
        if not all(a in H for a in ("base", "shaft", "capital")):
            out.append(row("E1", pid, "cne", "the stack holds %s, not a whole column"
                           % ", ".join(sorted(H)) or "nothing"))
            continue
        drawn = sum(H[a] for a in ("base", "shaft", "capital"))
        if abs(drawn - col) > 0.01:
            out.append(row("E1", pid, "disagrees", "states %.2f in, draws %.2f in (at a 6 in module)"
                           % (col, drawn)))
        else:
            out.append(row("E1", pid, "agrees"))
    return out


@check("E2", "order-stack", "the entablature drawn is the one the pack itself states",
       "order packs that state a whole entablature")
def e2():
    out = []
    PE = SURF._mod("proportion_engine")
    for pid, pack, dim, H in _order_packs():
        stated = dim["totals"].get("entablature_height_in")
        if not stated:
            continue
        drawn = sum(H.get(a, 0.0) for a in ("architrave", "frieze", "cornice", "entablature"))
        owner = PE.assembly_owner(pid, "entablature")
        if abs(drawn - stated) > 0.01:
            out.append(row("E2", pid, "disagrees",
                           "%s states %.2f in; the stack draws %.2f in from %s's %s"
                           % (owner, stated, drawn, PE.assembly_owner(pid, "cornice") or "nobody",
                              "architrave, frieze and cornice" if "cornice" in H else "entablature")))
        else:
            out.append(row("E2", pid, "agrees"))
    return out


@check("E3", "order-stack", "an assembly offered as an ALTERNATIVE to another is never stacked "
       "on it (Benjamin's subplinth stands a column instead of a pedestal)",
       "order packs stating a subplinth")
def e3():
    out = []
    for pid, pack, dim, H in _order_packs():
        if "subplinth" not in (pack.get("assemblies") or {}):
            continue
        stacked = [a["id"] for a in dim["assemblies"]]
        if "subplinth" in stacked and "pedestal" in stacked:
            out.append(row("E3", pid, "disagrees", "pedestal and subplinth both stacked (%.2f + %.2f in)"
                           % (H["pedestal"], H["subplinth"])))
        else:
            out.append(row("E3", pid, "agrees"))
    return out


# ------------------------------------------------------------------ running it
def run(only=None):
    rows = []
    for cid, c in CHECKS.items():
        if only and c["surface"] not in only and cid not in only:
            continue
        rows.extend(c["fn"]())
    return rows


def summary(rows):
    out = {}
    for cid, c in CHECKS.items():
        rs = [r for r in rows if r["check"] == cid]
        if not rs and cid not in {r["check"] for r in rows}:
            pass
        out[cid] = {"surface": c["surface"], "statement": c["statement"], "population": c["population"],
                    "rows": len(rs), "agrees": sum(r["verdict"] == "agrees" for r in rs),
                    "disagrees": sum(r["verdict"] == "disagrees" for r in rs),
                    "cne": sum(r["verdict"] == "cne" for r in rs)}
    return out


def disagreement_ids(rows):
    return sorted("%s:%s" % (r["check"], r["subject"]) for r in rows if r["verdict"] == "disagrees")


def render_doc_tables(rows):
    s = summary(rows)
    lines = ["| check | surface | statement | population | rows | agrees | disagrees | could not evaluate |",
             "|---|---|---|---|---:|---:|---:|---:|"]
    for cid, x in s.items():
        lines.append("| %s | %s | %s | %s | %d | %d | %d | %d |" % (
            cid, x["surface"], x["statement"], x["population"], x["rows"], x["agrees"],
            x["disagrees"], x["cne"]))
    reg = ["| id | role | file | surface / reason |", "|---|---|---|---|"]
    for r in REGISTRY:
        reg.append("| %s | %s | `%s` | %s |" % (r["id"], r["role"], r["file"],
                                                r.get("surface") or r.get("reason")))
    return "\n".join(reg), "\n".join(lines)


_MARK = ("<!-- census:%s:begin -->", "<!-- census:%s:end -->")


def splice(text, name, body):
    b, e = _MARK[0] % name, _MARK[1] % name
    i, j = text.index(b) + len(b), text.index(e)
    return text[:i] + "\n" + body + "\n" + text[j:]


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--write-doc", action="store_true")
    ap.add_argument("--surface", action="append")
    a = ap.parse_args()
    rows = run(set(a.surface) if a.surface else None)
    if a.json:
        print(json.dumps({"summary": summary(rows), "rows": rows}, indent=1))
        return 0
    if a.write_doc:
        reg, table = render_doc_tables(rows)
        text = open(DOC).read()
        text = splice(splice(text, "registry", reg), "checks", table)
        open(DOC, "w").write(text)
        print("wrote", os.path.relpath(DOC, ROOT))
        return 0
    for cid, x in summary(rows).items():
        print("%-4s %-18s agrees %4d  disagrees %4d  cne %4d   %s"
              % (cid, x["surface"], x["agrees"], x["disagrees"], x["cne"], x["statement"]))
    print("\nunregistered SVG emitters:", unregistered() or "none")
    return 0


if __name__ == "__main__":
    sys.exit(main())
