/* Which outline the atlas can honestly draw at the scale it is being read at.

   The map is an SVG plate with no tile server behind it, so zooming is a change of view
   box and nothing else: the coastline gets bigger, and — until this file existed — no
   sharper. One outline, Natural Earth 110m simplified at 0.55 degrees, held every scale
   from a hemisphere to a county, and past about ten degrees of longitude its corners
   were visible as facets. A vector that cannot gain detail as it grows is a raster with
   extra steps.

   So there are three outlines, generated by workbench/scripts/make_coastlines.py, and
   the map fetches the one its view can actually show. The coarse tier is imported
   eagerly because every view starts there; the other two are dynamic imports, which
   Vite splits into their own chunks, so a reader who never zooms never pays for them.

   THE HONESTY THAT MATTERS HERE is the same one the rest of the product keeps: while a
   finer tier is in flight, or if it failed to arrive, the map is drawing something
   coarser than the scale it is set to, and it says so rather than letting a facet pass
   for a coastline. `useCoastline` reports `drawn` (what is on the plate), `wanted` (what
   the scale deserves) and `failed` separately, and MapView prints the difference.

   THIS FILE IMPORTS NOTHING FROM node_modules, AND THAT IS LOAD-BEARING. The React hook
   that consumes it lives in `useCoastline.js` next door. `build/check_all.py` runs the
   app's `node --test` suite with no `npm install` — its own comment says "the app suite
   needs no npm install; it imports no packages" — and the corpus CI job relies on that.
   The first version of this file had `import React` at the top and the coastline test
   imported it, so the whole suite failed in CI while passing locally where node_modules
   happens to exist. `src/no_bare_imports.test.mjs` now walks the suite's import graph and
   fails on any bare specifier, so the next one is caught here rather than in CI. */
import { COAST_COARSE } from '../../data/coastlines.js';

/* `upto` is the widest view, in degrees of longitude, at which the tier is the right one
   to draw. The thresholds are where the coarser tier's own simplification tolerance
   starts to exceed about two screen pixels across a thousand-pixel pane — past that the
   error is a shape the reader can see, not a rounding. */
export const TIERS = [
  {
    name: 'coarse',
    upto: Infinity,
    load: () => Promise.resolve(COAST_COARSE),
  },
  {
    name: 'medium',
    upto: 70,
    load: () => import('../../data/coastlines-medium.js').then((m) => m.COAST_MEDIUM),
  },
  {
    name: 'fine',
    upto: 16,
    load: () => import('../../data/coastlines-fine.js').then((m) => m.COAST_FINE),
  },
];

/* Finest first, so `find` picks the best tier for a width. */
export const BY_DETAIL = TIERS.slice().reverse();

export function tierFor(width) {
  return BY_DETAIL.find((t) => width <= t.upto) || TIERS[0];
}

/* Visible rings only.

   The fine tier is 2,262 rings and a zoomed-in view holds a handful. Mounting the other
   two thousand paths for the viewBox to clip away is how a sharper coastline becomes a
   slower one — so the generator writes a bounding box per ring and this reads it. The
   boxes are rounded outward to whole degrees, which errs toward drawing one ring too
   many; the other error would be a hole in the world. */
export function visibleRings(tier, view) {
  if (!tier) return [];
  const { bounds, paths } = tier;
  const x0 = view.x, y0 = view.y, x1 = view.x + view.w, y1 = view.y + view.h;
  const out = [];
  for (let i = 0; i < paths.length; i += 1) {
    const b = i * 4;
    if (bounds[b] <= x1 && bounds[b + 2] >= x0 && bounds[b + 1] <= y1 && bounds[b + 3] >= y0) {
      out.push(i);
    }
  }
  return out;
}

/* Which loaded tier to draw for a given wanted tier: the NEAREST on the ladder, with a
   tie going to the finer. Pure, and exported, because both neighbouring rules were tried
   and both were wrong — see the note in `useCoastline` — and a rule that has been wrong
   twice deserves a test that does not need a DOM. */
export function chooseTier(wantedName, inHandNames) {
  const wantIdx = BY_DETAIL.findIndex((t) => t.name === wantedName);
  const order = BY_DETAIL.map((t) => t.name);
  return inHandNames.slice().sort((a, b) => {
    const da = Math.abs(order.indexOf(a) - wantIdx);
    const db = Math.abs(order.indexOf(b) - wantIdx);
    return da - db || order.indexOf(a) - order.indexOf(b);
  })[0] || TIERS[0].name;
}
