/* Which outline the atlas can honestly draw at the scale it is being read at.

   The map is an SVG plate with no tile server behind it, so zooming is a change of view
   box and nothing else: the coastline gets bigger, and — until this file existed — no
   sharper. One outline, Natural Earth 110m simplified at 0.55 degrees, held every scale
   from a hemisphere to a county, and past about ten degrees of longitude its corners
   were visible as facets. A vector that cannot gain detail as it grows is a raster with
   extra steps.

   So there are three outlines, generated by workbench/scripts/make_coastlines.py, and
   the map fetches the one its view can actually show. The coarse tier is imported
   eagerly because every view starts there; the other two are dynamic imports, which
   Vite splits into their own chunks, so a reader who never zooms never pays for them.

   THE HONESTY THAT MATTERS HERE is the same one the rest of the product keeps: while a
   finer tier is in flight, or if it failed to arrive, the map is drawing something
   coarser than the scale it is set to, and it says so rather than letting a facet pass
   for a coastline. `useCoastline` reports `drawn` (what is on the plate), `wanted` (what
   the scale deserves) and `failed` separately, and MapView prints the difference. */
import React from 'react';
import { COAST_COARSE } from '../../data/coastlines.js';

/* `upto` is the widest view, in degrees of longitude, at which the tier is the right one
   to draw. The thresholds are where the coarser tier's own simplification tolerance
   starts to exceed about two screen pixels across a thousand-pixel pane — past that the
   error is a shape the reader can see, not a rounding. */
export const TIERS = [
  {
    name: 'coarse',
    upto: Infinity,
    load: () => Promise.resolve(COAST_COARSE),
  },
  {
    name: 'medium',
    upto: 70,
    load: () => import('../../data/coastlines-medium.js').then((m) => m.COAST_MEDIUM),
  },
  {
    name: 'fine',
    upto: 16,
    load: () => import('../../data/coastlines-fine.js').then((m) => m.COAST_FINE),
  },
];

/* Finest first, so `find` picks the best tier for a width. */
const BY_DETAIL = TIERS.slice().reverse();

export function tierFor(width) {
  return BY_DETAIL.find((t) => width <= t.upto) || TIERS[0];
}

/* Module-scope, not component state: the fine tier is a megabyte and remounting the map
   — every trip to the tree reading and back — must not fetch it again. */
const loaded = new Map([['coarse', COAST_COARSE]]);
const failed = new Map();
const inflight = new Map();

/* Visible rings only.

   The fine tier is 2,262 rings and a zoomed-in view holds a handful. Mounting the other
   two thousand paths for the viewBox to clip away is how a sharper coastline becomes a
   slower one — so the generator writes a bounding box per ring and this reads it. The
   boxes are rounded outward to whole degrees, which errs toward drawing one ring too
   many; the other error would be a hole in the world. */
export function visibleRings(tier, view) {
  if (!tier) return [];
  const { bounds, paths } = tier;
  const x0 = view.x, y0 = view.y, x1 = view.x + view.w, y1 = view.y + view.h;
  const out = [];
  for (let i = 0; i < paths.length; i += 1) {
    const b = i * 4;
    if (bounds[b] <= x1 && bounds[b + 2] >= x0 && bounds[b + 1] <= y1 && bounds[b + 3] >= y0) {
      out.push(i);
    }
  }
  return out;
}

/* The tier the view deserves, the tier that is actually on the plate, and whether the
   difference is a fetch in flight or a fetch that failed. Never conflates the two: a
   coastline that could not be fetched is a stated gap, not a coarser drawing passed off
   as the right one. */
export function useCoastline(width) {
  const wanted = tierFor(width);
  const [, bump] = React.useReducer((n) => n + 1, 0);

  React.useEffect(() => {
    if (loaded.has(wanted.name) || failed.has(wanted.name)) return;
    if (inflight.has(wanted.name)) return;
    const p = wanted.load().then(
      (tier) => { loaded.set(wanted.name, tier); inflight.delete(wanted.name); bump(); },
      (err) => {
        // Recorded, not retried in a loop: a chunk that will not load will not load on
        // the next pointer move either, and a hundred failed fetches a second is worse
        // than a coarse coastline.
        failed.set(wanted.name, err && err.message ? err.message : String(err));
        inflight.delete(wanted.name);
        bump();
      },
    );
    inflight.set(wanted.name, p);
  }, [wanted.name]);

  // Best available: the finest tier already in hand that is no finer than what is wanted.
  const from = BY_DETAIL.indexOf(wanted);
  const drawn = BY_DETAIL.slice(from).find((t) => loaded.has(t.name)) || TIERS[0];
  return {
    wanted,
    drawn: loaded.get(drawn.name) || COAST_COARSE,
    drawnName: drawn.name,
    pending: drawn.name !== wanted.name && !failed.has(wanted.name),
    failed: failed.get(wanted.name) || null,
  };
}
