/* The Proportions plate's arithmetic (WP-14.1), read without React.

   proportions/plate.js was lifted out of surfaces/Proportions.jsx so that what the plate computes
   -- its frame, the datum it states, which members it says publish no projection -- could be read
   by something other than a browser. What it computes WRONG is held by the census
   (tests/svg_census.py, checks R1-R3, and docs/fidelity.md), which runs this same module on every
   order pack against the ink Python serves. These tests hold the properties that are true of the
   plate whatever is fixed later, on fixtures that are exactly what the server serves, trimmed to
   the fields the module reads (tests/fixtures/proportions_plate/, regenerated by its generate.py
   and held current by tests/test_svg_census.py).

   They import nothing but the module under test and node's own libraries: the app suite runs
   under `node --test` with no npm install, and src/no_bare_imports.test.mjs walks the graph. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { plateGeometry, stackWords } from './proportions/plate.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIX = join(HERE, '..', '..', '..', 'tests', 'fixtures', 'proportions_plate');
const fixtures = readdirSync(FIX).filter((f) => f.endsWith('.json')).sort()
  .map((f) => [f, JSON.parse(readFileSync(join(FIX, f), 'utf8'))]);

test('there are fixtures, one for each datum the plate can be asked to draw', () => {
  assert.equal(fixtures.length, 3);
  const datums = new Set(fixtures.map(([, d]) => d.projection_datum));
  assert.deepEqual([...datums].sort(), ['axis', 'naked']);
});

test('a pack with no stack draws no plate, rather than a frame around nothing', () => {
  assert.equal(plateGeometry({ assemblies: [], totals: {} }), null);
});

for (const [name, data] of fixtures) {
  test(`${name}: one band per member the engine emitted, none added and none dropped`, () => {
    const P = plateGeometry(data);
    const members = data.assemblies.reduce((n, a) => n + a.members.length, 0);
    assert.equal(P.bands.length, members);
    const keys = new Set(P.bands.map((b) => b.key));
    for (const a of data.assemblies) for (const m of a.members) assert.ok(keys.has(`${a.id}.${m.id}`));
  });

  test(`${name}: the plate is as tall as the stack the engine dimensioned`, () => {
    const P = plateGeometry(data);
    assert.equal(P.H, data.totals.stack_height_in);
  });

  test(`${name}: the column is drawn at the diameter the record states`, () => {
    const P = plateGeometry(data);
    assert.equal(P.r0, data.totals.lower_diameter_in / 2);
    assert.equal(P.nominal, false);
  });

  test(`${name}: every band with served geometry is drawn from it, not from a straight edge`, () => {
    const P = plateGeometry(data);
    let served = 0;
    for (const b of P.bands) {
      const bp = P.bandPath(b);
      if (P.segsFor[b.key] && P.segsFor[b.key].path) {
        served += 1;
        assert.equal(bp.d, P.segsFor[b.key].path);
        assert.ok(bp.transform && bp.transform.startsWith('translate(0,'), bp.transform);
      } else {
        assert.equal(bp.transform, null);
      }
    }
    assert.ok(served > 0, 'no band carried served geometry, so this test checked nothing');
  });

  test(`${name}: the stated datum is the one the pack declares`, () => {
    const P = plateGeometry(data);
    assert.equal(P.fromAxis, data.projection_datum === 'axis');
    assert.equal(P.undeclared, !data.projection_datum);
  });

  // WP-14.2: everything below is read off the served geometry and scaled, never computed here.
  test(`${name}: the frame is the ink's own extent, as Python measured it`, () => {
    const P = plateGeometry(data);
    const f = data.module_in / data.geometry.module_in;
    assert.ok(data.geometry.bbox_in, 'premise: the fixture serves an extent');
    assert.equal(P.maxX, data.geometry.bbox_in.x1 * f);
  });

  test(`${name}: every band stands at the face Python constructed for it`, () => {
    const P = plateGeometry(data);
    const f = data.module_in / data.geometry.module_in;
    const faces = {};
    for (const a of data.geometry.assemblies) for (const fc of a.faces) faces[`${a.id}.${fc.id}`] = fc;
    let n = 0;
    for (const b of P.bands) {
      const fc = faces[b.key];
      assert.ok(fc, `${b.key}: no served face`);
      assert.equal(b.x1, fc.x * f, b.key);
      assert.equal(b.x0, (fc.tapered ? fc.x_from : fc.x) * f, b.key);
      n += 1;
    }
    assert.ok(n > 20, `only ${n} bands`);
  });

  test(`${name}: the members it calls unpublished are exactly the ones Python drew no face for`, () => {
    const P = plateGeometry(data);
    const served = data.geometry.unpublished.map((u) => `${u.assembly}.${u.id}`).sort();
    assert.deepEqual([...P.unrecorded].sort(), served);
    for (const b of P.bands) assert.equal(b.unpublished, served.includes(b.key), b.key);
  });

  test(`${name}: the caption names each assembly under the datum it was drawn on`, () => {
    const P = plateGeometry(data);
    const PHRASE = { axis: 'from the axis for the ', naked: 'from each member’s own naked for the ',
                     unjudged: 'No datum can be read for the ' };
    for (const [asm, d] of Object.entries(data.geometry.assembly_datum)) {
      const at = P.datumWords.indexOf(PHRASE[d]);
      assert.ok(at >= 0, `${asm}: no clause for ${d} in "${P.datumWords}"`);
      const clause = P.datumWords.slice(at + PHRASE[d].length).split(/[;:.]| —/)[0];
      assert.ok(new RegExp(`\\b${asm}\\b`).test(clause), `${asm} is not in the ${d} clause "${clause}"`);
    }
  });
}

test('the fixtures reach a pack whose base publishes nothing, so its die is not derived', () => {
  const [, data] = fixtures.find(([n]) => n.startsWith('palladio-ionic'));
  const P = plateGeometry(data);
  assert.equal(data.geometry.die_naked, 'unjudged', 'premise');
  assert.equal(P.dieNaked, null);
  assert.ok(P.dieReason && P.dieReason.includes('base'), P.dieReason);
  assert.ok(P.unrecorded.size > 0, 'premise: palladio-ionic publishes no projection for some members');
});

test('the fixtures reach a derived die, and it is the served figure scaled', () => {
  const [, data] = fixtures.find(([n]) => n.startsWith('gibbs-doric'));
  const P = plateGeometry(data);
  assert.equal(data.geometry.die_naked, 'derived', 'premise');
  assert.equal(P.dieNaked, data.geometry.die_naked_in * (data.module_in / data.geometry.module_in));
});

test('every figure read off the geometry scales with the module the plate draws at', () => {
  /* The server builds the geometry at the module it is asked for, so on every fixture f is 1 and a
     plate that forgot to scale would pass every test above. Here the plate is asked for twice the
     module the geometry was built at: the frame, every band and the die must all double. */
  const [, data] = fixtures.find(([n]) => n.startsWith('gibbs-doric'));
  const one = plateGeometry(data);
  const two = plateGeometry({ ...data, module_in: data.geometry.module_in * 2 });
  assert.equal(one.f, 1, 'premise: the fixture is served at the module it draws');
  assert.equal(two.f, 2);
  assert.equal(two.maxX, data.geometry.bbox_in.x1 * 2);
  assert.equal(two.dieNaked, data.geometry.die_naked_in * 2);
  for (const [a, b] of one.bands.map((b, i) => [b, two.bands[i]])) {
    assert.equal(b.x1, a.x1 * 2, a.key);
    assert.equal(b.x0, a.x0 * 2, a.key);
  }
});

test('what the stack left out is said, one sentence each, and nothing when it left nothing out', () => {
  /* The three fixtures leave nothing out, so the words are driven here in the shape
     proportion_engine.stack_notes serves (census R4 holds them to every pack). */
  assert.equal(stackWords([]), '');
  const both = stackWords([
    { kind: 'alternative', assembly: 'subplinth', instead_of: 'pedestal', drawn: 'pedestal' },
    { kind: 'entablature-whole', assembly: 'entablature', owner: 'benjamin-corinthian',
      triplet_owners: { architrave: 'vignola-corinthian', frieze: 'vignola-corinthian', cornice: 'vignola-corinthian' } },
  ]);
  assert.match(both, /The subplinth is not drawn: it is offered instead of the pedestal, never on it\./);
  assert.match(both, /The entablature is drawn whole, as benjamin-corinthian states it: .* from vignola-corinthian add up/);
  for (const [, data] of fixtures) assert.equal(plateGeometry(data).stackWords, '', data.pack);
});

test('a pack served without geometry is drawn at the radius and says it has none', () => {
  const [, data] = fixtures[0];
  const P = plateGeometry({ ...data, geometry: null });
  assert.equal(P.noGeometry, true);
  for (const b of P.bands) assert.equal(b.x1, P.r0, b.key);
  assert.equal(P.unrecorded.size, 0);
});
