/* The Proportions plate's arithmetic (WP-14.1), read without React.

   proportions/plate.js was lifted out of surfaces/Proportions.jsx so that what the plate computes
   -- its frame, the datum it states, which members it says publish no projection -- could be read
   by something other than a browser. What it computes WRONG is held by the census
   (tests/svg_census.py, checks R1-R3, and docs/fidelity.md), which runs this same module on every
   order pack against the ink Python serves. These tests hold the properties that are true of the
   plate whatever is fixed later, on fixtures that are exactly what the server serves, trimmed to
   the fields the module reads (tests/fixtures/proportions_plate/, regenerated by its generate.py
   and held current by tests/test_svg_census.py).

   They import nothing but the module under test and node's own libraries: the app suite runs
   under `node --test` with no npm install, and src/no_bare_imports.test.mjs walks the graph. */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { plateGeometry } from './proportions/plate.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIX = join(HERE, '..', '..', '..', 'tests', 'fixtures', 'proportions_plate');
const fixtures = readdirSync(FIX).filter((f) => f.endsWith('.json')).sort()
  .map((f) => [f, JSON.parse(readFileSync(join(FIX, f), 'utf8'))]);

test('there are fixtures, one for each datum the plate can be asked to draw', () => {
  assert.equal(fixtures.length, 3);
  const datums = new Set(fixtures.map(([, d]) => d.projection_datum));
  assert.deepEqual([...datums].sort(), ['axis', 'naked']);
});

test('a pack with no stack draws no plate, rather than a frame around nothing', () => {
  assert.equal(plateGeometry({ assemblies: [], totals: {} }), null);
});

for (const [name, data] of fixtures) {
  test(`${name}: one band per member the engine emitted, none added and none dropped`, () => {
    const P = plateGeometry(data);
    const members = data.assemblies.reduce((n, a) => n + a.members.length, 0);
    assert.equal(P.bands.length, members);
    const keys = new Set(P.bands.map((b) => b.key));
    for (const a of data.assemblies) for (const m of a.members) assert.ok(keys.has(`${a.id}.${m.id}`));
  });

  test(`${name}: the plate is as tall as the stack the engine dimensioned`, () => {
    const P = plateGeometry(data);
    assert.equal(P.H, data.totals.stack_height_in);
  });

  test(`${name}: the column is drawn at the diameter the record states`, () => {
    const P = plateGeometry(data);
    assert.equal(P.r0, data.totals.lower_diameter_in / 2);
    assert.equal(P.nominal, false);
  });

  test(`${name}: every band with served geometry is drawn from it, not from a straight edge`, () => {
    const P = plateGeometry(data);
    let served = 0;
    for (const b of P.bands) {
      const bp = P.bandPath(b);
      if (P.segsFor[b.key] && P.segsFor[b.key].path) {
        served += 1;
        assert.equal(bp.d, P.segsFor[b.key].path);
        assert.ok(bp.transform && bp.transform.startsWith('translate(0,'), bp.transform);
      } else {
        assert.equal(bp.transform, null);
      }
    }
    assert.ok(served > 0, 'no band carried served geometry, so this test checked nothing');
  });

  test(`${name}: the stated datum is the one the pack declares`, () => {
    const P = plateGeometry(data);
    assert.equal(P.fromAxis, data.projection_datum === 'axis');
    assert.equal(P.undeclared, !data.projection_datum);
  });
}
