/* Surface ⑧b — Details & Export. What works today works plainly: the plan record,
   the brief, the check report and every generated SVG leave as files. What is not
   built is present, disabled, and named with its work package — forthcoming, never
   hidden. The interface must not imply a completeness the corpus does not have. */
import React from 'react';
import { api } from '../api/client.js';
import { planDoc } from '../state/planDoc.js';
import { session } from '../state/session.js';
import { Eyebrow } from '../components/Eyebrow.jsx';
import { FilterStrip, Chip, ActionChip } from '../Chrome.jsx';
import { ConflictSet } from '../components/ConflictSet.jsx';
import { evaluateRefusal, placementRefusal, sketchOf, errorText, refusalFromError, isMissingLibrary }
  from '../sheet/refusal.js';

function save(name, content, type = 'application/json') {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob(
    [typeof content === 'string' ? content : JSON.stringify(content, null, 1)], { type }));
  a.download = name;
  a.click();
  URL.revokeObjectURL(a.href);
}

const card = { border: '1px solid var(--rule)', padding: '14px 16px', flex: '1 1 300px',
  minWidth: 280, maxWidth: 420 };
const cardTitle = { font: 'var(--fw-reg) 17px/1.2 var(--display)', color: 'var(--ink)', margin: '0 0 7px' };
const cardBody = { font: 'var(--fw-reg) 13px/1.55 var(--body)', color: 'var(--ink-2)', margin: '0 0 12px' };

export function ExportDetails({ lastEval }) {
  const plan = React.useSyncExternalStore(planDoc.subscribe, planDoc.get);
  const s = React.useSyncExternalStore(session.subscribe, session.get);
  const [busySvg, setBusySvg] = React.useState(null);
  const [busyCad, setBusyCad] = React.useState(null);
  const [note, setNote] = React.useState(null);
  const [refusal, setRefusal] = React.useState(null);
  /* The fault count below is the corpus's, read from /api/overview: it was typed as "209"
     against a corpus of 210 (WP-14.13). Unread, the sentence names no figure. */
  const [faultCount, setFaultCount] = React.useState(null);
  React.useEffect(() => {
    let live = true;
    api.overview().then((o) => { if (live) setFaultCount(o?.counts?.faults ?? null); }).catch(() => {});
    return () => { live = false; };
  }, []);

  /* NOTHING LEAVES THIS SYSTEM FROM A REFUSED PLACEMENT, AND NOTHING LEAVES IT FROM A SKETCH
     (WP-13.4). The verdict is the one the bench already holds — `/api/plan/evaluate`'s own
     `placement_refused`, or the placed record's `geometry_report.refused`, or the wall drag's
     `placement.sketch` — read through `sheet/refusal.js` and derived nowhere here. A working
     sketch is a legitimate thing to look at and is never a legitimate thing to hand a drafter,
     so it blocks an export while it does not block the bench's own plate. */
  const evalRefusal = evaluateRefusal(lastEval) || placementRefusal(lastEval?.placement);
  const sketch = sketchOf(lastEval?.placement);
  const blocked = Boolean(evalRefusal) || Boolean(sketch);
  const blockedWhy = evalRefusal
    ? 'the placement was refused — nothing may be exported from it'
    : sketch
      ? 'the bench is showing a working sketch from a wall drag — a sketch is never a file'
      : '';
  const shown = refusal || evalRefusal;

  /* THE ROUTES GO THROUGH `api/client.js` NOW, AND A REFUSAL REACHES THE READER.
     `saveSvg` was a raw fetch with `if (r.ok)` and NO else, so a 422 downloaded nothing and
     said nothing — a button that appeared to do its job and did not. `saveCad` painted every
     failure in `var(--forthcoming)`, the colour this surface reserves for what is DESIGNED AND
     NOT BUILT, so a refused house read as a missing feature. Both report through the one leaf:
     a refused placement shows its conflict set, a 501 keeps saying the server has no CAD
     library, and anything else is stated as itself. */
  async function saveSvg(kind) {
    if (!plan || blocked) return;
    setBusySvg(kind); setNote(null); setRefusal(null);
    try {
      const j = await api.drawing(kind, plan);
      save(`${plan.id}-${kind}.svg`, j.svg, 'image/svg+xml');
    } catch (e) {
      const r = refusalFromError(e);
      if (r) setRefusal(r);
      else setNote({ text: errorText(e) || 'the drawing could not be generated',
        missing: isMissingLibrary(e) });
    } finally {
      setBusySvg(null);
    }
  }

  /* WP-5.1: DXF sheets and the IFC model, generated by the same build/ modules
     the CLI drives. A refusal (missing optional library on the server, an
     elevation outside the classical-front family) is shown stated, not
     swallowed into an empty download. */
  async function saveCad(fmt, kind) {
    if (!plan || blocked) return;
    const key = kind ? `${fmt}:${kind}` : fmt;
    setBusyCad(key); setNote(null); setRefusal(null);
    try {
      const j = await api.exportCad(fmt, plan, kind ? { kind } : {});
      save(j.filename, j.text, fmt === 'dxf' ? 'application/dxf' : 'application/x-step');
    } catch (e) {
      const r = refusalFromError(e);
      if (r) setRefusal(r);
      else setNote({ text: errorText(e) || 'the export failed', missing: isMissingLibrary(e) });
    } finally {
      setBusyCad(null);
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: 0, flex: 1 }}>
      <FilterStrip>
        <Eyebrow as="span">details &amp; export</Eyebrow>
        <span style={{ font: 'var(--type-data-s)', color: 'var(--ink-4)' }}>
          generated from data, so it cannot drift — and honest about what is not built
        </span>
      </FilterStrip>

      <div style={{ flex: 1, overflow: 'auto', minHeight: 0, padding: '22px 26px 36px' }}>
        {/* WHAT MAY NOT LEAVE, AND WHY, BEFORE THE BUTTONS THAT WOULD HAVE SENT IT (WP-13.4).
            The conflict set is the same component the bench draws where the plate would be, so
            a reader who came here from a refused sheet meets the same words rather than a
            second account of one verdict. */}
        <ConflictSet refusal={shown} where="every export of this record" />
        {note && (
          <p data-export-note={note.missing ? 'missing-library' : 'error'}
            style={{ font: 'var(--type-data-s)',
              // the NOT-BUILT colour is for what is not built. An export that FAILED is not a
              // forthcoming feature, and painting the two the same made a refused house read
              // as a gap in the product.
              color: note.missing ? 'var(--forthcoming)' : 'var(--sev-serious)',
              margin: '0 0 14px', maxWidth: '76ch' }}>
            {note.missing
              ? `not built on this server — ${note.text}`
              : `refused — ${note.text}`}
          </p>
        )}
        <Eyebrow style={{ marginBottom: 12 }}>leaves the system today</Eyebrow>
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', alignItems: 'stretch' }}>
          <div style={card}>
            <h3 style={cardTitle}>The plan record</h3>
            <p style={cardBody}>
              The IR itself — the record every drawing and finding renders from. Clear
              dimensions, declared walls, doors, assertions. JSON against
              <span style={{ fontFamily: 'var(--mono)' }}> schema/plan.schema.json</span>.
            </p>
            <ActionChip affix="↓" disabled={!plan} onClick={plan ? () => save(`${plan.id}.json`, plan) : undefined}
              title={plan ? '' : 'no plan on the bench'}>
              {plan ? `download ${plan.id}.json` : 'no plan on the bench'}
            </ActionChip>
          </div>
          <div style={card}>
            <h3 style={cardTitle}>The brief &amp; the check report</h3>
            <p style={cardBody}>
              The brief as typed, and the validator's latest full report — counts, findings,
              constraint summary and the could-not-judge list, none of it collapsed.
            </p>
            <span style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              <ActionChip affix="↓" disabled={!s.brief} onClick={s.brief ? () => save(`${s.brief.id || 'brief'}.json`, s.brief) : undefined}>
                {s.brief ? 'download brief' : 'no brief drafted'}
              </ActionChip>
              <ActionChip affix="↓" disabled={!lastEval?.check} onClick={lastEval?.check ? () => save(`${plan?.id || 'plan'}-check.json`, lastEval) : undefined}>
                {lastEval?.check ? 'download check report' : 'no evaluation yet'}
              </ActionChip>
            </span>
          </div>
          <div style={card}>
            <h3 style={cardTitle}>The drawing set, as SVG</h3>
            <p style={cardBody}>
              Every sheet the generators produce, in the Drawn Language. The drawing is a
              render of the record; export re-renders, it never snapshots the screen.
            </p>
            <span style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {['plan', 'elevation', 'section', 'bearing', 'roof'].map((k) => (
                <ActionChip key={k} affix={busySvg === k ? '…' : '↓'} disabled={!plan || blocked}
                  title={blocked ? blockedWhy : ''}
                  onClick={plan && !blocked ? () => saveSvg(k) : undefined}>
                  {busySvg === k ? 'generating…' : k}
                </ActionChip>
              ))}
            </span>
          </div>
          <div style={card}>
            <h3 style={cardTitle}>DXF &amp; IFC (WP-5.1)</h3>
            <p style={cardBody}>
              Layered DXF per sheet, in inches, the record riding on the entities as XDATA —
              round-trip proven: DXF → plan record → validator gives the same findings. And an
              IFC4 model: walls, slabs, openings, roof and spaces, every product carrying its
              TDL ids in a <span style={{ fontFamily: 'var(--mono)' }}>TDL</span> property set.
            </p>
            <span style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {['plan', 'section', 'roof', 'elevation'].map((k) => (
                <ActionChip key={k} affix={busyCad === `dxf:${k}` ? '…' : '↓'}
                  disabled={!plan || blocked} title={blocked ? blockedWhy : ''}
                  onClick={plan && !blocked ? () => saveCad('dxf', k) : undefined}>
                  {busyCad === `dxf:${k}` ? 'generating…' : `${k} dxf`}
                </ActionChip>
              ))}
              <ActionChip affix={busyCad === 'ifc' ? '…' : '↓'} disabled={!plan || blocked}
                title={blocked ? blockedWhy : ''}
                onClick={plan && !blocked ? () => saveCad('ifc') : undefined}>
                {busyCad === 'ifc' ? 'generating…' : 'ifc model'}
              </ActionChip>
            </span>
            {blocked && (
              <p data-export-blocked="" style={{ font: 'var(--type-data-s)',
                color: 'var(--refusal)', margin: '10px 0 0' }}>{blockedWhy}</p>
            )}
          </div>
        </div>

        <Eyebrow style={{ margin: '28px 0 12px' }}>forthcoming — designed, not built, and saying so</Eyebrow>
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', alignItems: 'stretch' }}>
          {[
            { t: 'Design guidelines, per style', wp: 'WP-5.3', body:
              'A generated book per style: constraints, forbidden variants, faults with their ' +
              'exceptions, pack bindings, rendered orders and details. HTML and PDF, from data, ' +
              'so it cannot drift.' },
            { t: 'The details library', wp: 'WP-5.3', body:
              'Every measured detail rendered by the engine, and all 262 recorded pack conflicts ' +
              'with their resolution prose. Ranked substitution sets are planned structure the ' +
              'corpus does not yet hold — this card will not pretend otherwise.' },
          ].map((c) => (
            <div key={c.t} data-not-built="" style={{ ...card, backgroundImage: 'var(--mark-not-built)' }}>
              <div style={{ background: 'var(--paper)', padding: '8px 10px' }}>
                <h3 style={{ ...cardTitle, color: 'var(--ink-2)' }}>{c.t}</h3>
                <p style={{ ...cardBody, color: 'var(--ink-3)', marginBottom: 8 }}>{c.body}</p>
                <span style={{ font: 'var(--type-data-s)', color: 'var(--forthcoming)' }}>
                  forthcoming — {c.wp} is not built
                </span>
              </div>
            </div>
          ))}
        </div>

        <p style={{ font: 'var(--fw-reg) 12.5px/1.6 var(--body)', color: 'var(--ink-3)',
          margin: '16px 0 0', maxWidth: '76ch' }}>
          Drawing-to-record ingestion was named forthcoming here until it existed; it shipped
          as the Transcription surface (WP-5.5) — a drawing goes in by tracing or a
          drafter&rsquo;s DXF, and a record comes out with its gaps named.
        </p>

        <p style={{ font: 'var(--fw-reg) 12.5px/1.6 var(--body)', color: 'var(--ink-3)',
          margin: '24px 0 0', maxWidth: '76ch' }}>
          No costing engine exists: every one of the{faultCount != null ? ` ${faultCount}` : ''} faults carries a recorded{' '}
          <span style={{ fontFamily: 'var(--mono)' }}>cost_saved</span> (86 of them priced in
          dollars) and nothing here prices a plan. Code findings are advisory IRC model text
          and are never rendered as compliance.
        </p>
      </div>
    </div>
  );
}
