/* Surface ⑧b — Details & Export. What works today works plainly: the plan record,
   the brief, the check report and every generated SVG leave as files. What is not
   built is present, disabled, and named with its work package — forthcoming, never
   hidden. The interface must not imply a completeness the corpus does not have. */
import React from 'react';
import { api } from '../api/client.js';
import { planDoc } from '../state/planDoc.js';
import { session } from '../state/session.js';
import { Eyebrow } from '../components/Eyebrow.jsx';
import { FilterStrip, Chip, ActionChip } from '../Chrome.jsx';

function save(name, content, type = 'application/json') {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob(
    [typeof content === 'string' ? content : JSON.stringify(content, null, 1)], { type }));
  a.download = name;
  a.click();
  URL.revokeObjectURL(a.href);
}

const card = { border: '1px solid var(--rule)', padding: '14px 16px', flex: '1 1 300px',
  minWidth: 280, maxWidth: 420 };
const cardTitle = { font: 'var(--fw-reg) 17px/1.2 var(--display)', color: 'var(--ink)', margin: '0 0 7px' };
const cardBody = { font: 'var(--fw-reg) 13px/1.55 var(--body)', color: 'var(--ink-2)', margin: '0 0 12px' };

export function ExportDetails({ lastEval }) {
  const plan = React.useSyncExternalStore(planDoc.subscribe, planDoc.get);
  const s = React.useSyncExternalStore(session.subscribe, session.get);
  const [busySvg, setBusySvg] = React.useState(null);
  const [busyCad, setBusyCad] = React.useState(null);
  const [cadNote, setCadNote] = React.useState(null);

  async function saveSvg(kind) {
    if (!plan) return;
    setBusySvg(kind);
    try {
      const r = await fetch(`/api/drawings/${kind}`, {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ plan }),
      });
      const j = await r.json();
      if (r.ok) save(`${plan.id}-${kind}.svg`, j.svg, 'image/svg+xml');
    } finally {
      setBusySvg(null);
    }
  }

  /* WP-5.1: DXF sheets and the IFC model, generated by the same build/ modules
     the CLI drives. A refusal (missing optional library on the server, an
     elevation outside the classical-front family) is shown stated, not
     swallowed into an empty download. */
  async function saveCad(fmt, kind) {
    if (!plan) return;
    const key = kind ? `${fmt}:${kind}` : fmt;
    setBusyCad(key);
    setCadNote(null);
    try {
      const r = await fetch(`/api/export/${fmt}`, {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ plan, kind }),
      });
      const j = await r.json();
      if (r.ok) {
        save(j.filename, j.text,
          fmt === 'dxf' ? 'application/dxf' : 'application/x-step');
      } else {
        const d = j.detail || j;
        setCadNote(d.refusal ? `refused — ${d.error}` : d.error || 'export failed');
      }
    } catch (e) {
      setCadNote(String(e));
    } finally {
      setBusyCad(null);
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', minHeight: 0, flex: 1 }}>
      <FilterStrip>
        <Eyebrow as="span">details &amp; export</Eyebrow>
        <span style={{ font: 'var(--type-data-s)', color: 'var(--ink-4)' }}>
          generated from data, so it cannot drift — and honest about what is not built
        </span>
      </FilterStrip>

      <div style={{ flex: 1, overflow: 'auto', minHeight: 0, padding: '22px 26px 36px' }}>
        <Eyebrow style={{ marginBottom: 12 }}>leaves the system today</Eyebrow>
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', alignItems: 'stretch' }}>
          <div style={card}>
            <h3 style={cardTitle}>The plan record</h3>
            <p style={cardBody}>
              The IR itself — the record every drawing and finding renders from. Clear
              dimensions, declared walls, doors, assertions. JSON against
              <span style={{ fontFamily: 'var(--mono)' }}> schema/plan.schema.json</span>.
            </p>
            <ActionChip affix="↓" disabled={!plan} onClick={plan ? () => save(`${plan.id}.json`, plan) : undefined}
              title={plan ? '' : 'no plan on the bench'}>
              {plan ? `download ${plan.id}.json` : 'no plan on the bench'}
            </ActionChip>
          </div>
          <div style={card}>
            <h3 style={cardTitle}>The brief &amp; the check report</h3>
            <p style={cardBody}>
              The brief as typed, and the validator's latest full report — counts, findings,
              constraint summary and the could-not-judge list, none of it collapsed.
            </p>
            <span style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              <ActionChip affix="↓" disabled={!s.brief} onClick={s.brief ? () => save(`${s.brief.id || 'brief'}.json`, s.brief) : undefined}>
                {s.brief ? 'download brief' : 'no brief drafted'}
              </ActionChip>
              <ActionChip affix="↓" disabled={!lastEval?.check} onClick={lastEval?.check ? () => save(`${plan?.id || 'plan'}-check.json`, lastEval) : undefined}>
                {lastEval?.check ? 'download check report' : 'no evaluation yet'}
              </ActionChip>
            </span>
          </div>
          <div style={card}>
            <h3 style={cardTitle}>The drawing set, as SVG</h3>
            <p style={cardBody}>
              Every sheet the generators produce, in the Drawn Language. The drawing is a
              render of the record; export re-renders, it never snapshots the screen.
            </p>
            <span style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {['plan', 'elevation', 'section', 'bearing', 'roof'].map((k) => (
                <ActionChip key={k} affix={busySvg === k ? '…' : '↓'} disabled={!plan} onClick={plan ? () => saveSvg(k) : undefined}>
                  {busySvg === k ? 'generating…' : k}
                </ActionChip>
              ))}
            </span>
          </div>
          <div style={card}>
            <h3 style={cardTitle}>DXF &amp; IFC (WP-5.1)</h3>
            <p style={cardBody}>
              Layered DXF per sheet, in inches, the record riding on the entities as XDATA —
              round-trip proven: DXF → plan record → validator gives the same findings. And an
              IFC4 model: walls, slabs, openings, roof and spaces, every product carrying its
              TDL ids in a <span style={{ fontFamily: 'var(--mono)' }}>TDL</span> property set.
            </p>
            <span style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {['plan', 'section', 'roof', 'elevation'].map((k) => (
                <ActionChip key={k} affix={busyCad === `dxf:${k}` ? '…' : '↓'} disabled={!plan}
                  onClick={plan ? () => saveCad('dxf', k) : undefined}>
                  {busyCad === `dxf:${k}` ? 'generating…' : `${k} dxf`}
                </ActionChip>
              ))}
              <ActionChip affix={busyCad === 'ifc' ? '…' : '↓'} disabled={!plan} onClick={plan ? () => saveCad('ifc') : undefined}>
                {busyCad === 'ifc' ? 'generating…' : 'ifc model'}
              </ActionChip>
            </span>
            {cadNote && (
              <p style={{ font: 'var(--type-data-s)', color: 'var(--forthcoming)',
                margin: '10px 0 0' }}>{cadNote}</p>
            )}
          </div>
        </div>

        <Eyebrow style={{ margin: '28px 0 12px' }}>forthcoming — designed, not built, and saying so</Eyebrow>
        <div style={{ display: 'flex', gap: 16, flexWrap: 'wrap', alignItems: 'stretch' }}>
          {[
            { t: 'Design guidelines, per style', wp: 'WP-5.3', body:
              'A generated book per style: constraints, forbidden variants, faults with their ' +
              'exceptions, pack bindings, rendered orders and details. HTML and PDF, from data, ' +
              'so it cannot drift.' },
            { t: 'The details library', wp: 'WP-5.3', body:
              'Every measured detail rendered by the engine, and all 262 recorded pack conflicts ' +
              'with their resolution prose. Ranked substitution sets are planned structure the ' +
              'corpus does not yet hold — this card will not pretend otherwise.' },
          ].map((c) => (
            <div key={c.t} style={{ ...card, backgroundImage: 'var(--hatch-45)' }}>
              <div style={{ background: 'var(--paper)', padding: '8px 10px' }}>
                <h3 style={{ ...cardTitle, color: 'var(--ink-2)' }}>{c.t}</h3>
                <p style={{ ...cardBody, color: 'var(--ink-3)', marginBottom: 8 }}>{c.body}</p>
                <span style={{ font: 'var(--type-data-s)', color: 'var(--forthcoming)' }}>
                  forthcoming — {c.wp} is not built
                </span>
              </div>
            </div>
          ))}
        </div>

        <p style={{ font: 'var(--fw-reg) 12.5px/1.6 var(--body)', color: 'var(--ink-3)',
          margin: '16px 0 0', maxWidth: '76ch' }}>
          Drawing-to-record ingestion was named forthcoming here until it existed; it shipped
          as the Transcription surface (WP-5.5) — a drawing goes in by tracing or a
          drafter&rsquo;s DXF, and a record comes out with its gaps named.
        </p>

        <p style={{ font: 'var(--fw-reg) 12.5px/1.6 var(--body)', color: 'var(--ink-3)',
          margin: '24px 0 0', maxWidth: '76ch' }}>
          No costing engine exists: every one of the 209 faults carries a recorded{' '}
          <span style={{ fontFamily: 'var(--mono)' }}>cost_saved</span> (86 of them priced in
          dollars) and nothing here prices a plan. Code findings are advisory IRC model text
          and are never rendered as compliance.
        </p>
      </div>
    </div>
  );
}
